(function(g){var window=this;var r7=function(a,b){return g.aa[a]=b},Ota=function(a,b){var c=new g.yI;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.isDefault=!1;c.G=a.G;c.F=a.F;c.H=a.H;c.g=b;return c},s7=function(a){return a.g?a.g.languageCode:a.o},t7=function(a){var b={format:a.A,
languageCode:a.o,languageName:a.D,displayName:g.zI(a),kind:a.B,name:a.C,id:a.Aa,is_servable:a.M,is_default:a.isDefault,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},u7=function(a){if(!Pta.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Qta,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},Rta=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},Sta=function(a){for(var b in a)delete a[b]},v7=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.aT.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.B=f;this.o=k},w7=function(a,b,c,d,e){g.aT.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},y7=function(a){a=void 0===a?{}:a;
var b="_"+x7++;return new w7(0,0x8000000000000,0,b,a)},B7=function(a,b,c,d,e,f){var k={};
g.za(k,b);g.za(k,a.params);g.za(k,c);var l={};g.za(l,b.jb);a.params.jb&&g.za(l,a.params.jb);g.za(l,c.jb);k.jb=l;g.X.call(this,{K:"div",X:"caption-window",Z:{id:"caption-window-"+a.id,dir:k.vj==z7.Xo?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:k.lang},O:[{K:"span",X:"captions-text"}]});this.B=[];this.H=!1;this.C=a;this.F=[];this.G=[];this.za=e;this.va=f;this.D=null;this.N=.96*e;this.fa=.96*f;this.g=k;this.pa=c;this.A=this.wa["captions-text"];this.ka=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.J=d/360*16;this.type=A7.Uo;this.aa=this.J*Tta(l);a=new g.cG(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.dJ,this);a.subscribe("dragmove",this.cJ,this);a.subscribe("dragend",this.bJ,this);this.da=this.ca=0;a="";this.g.Bj&&(a=u7(this.g.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.g.Bj+")");b={"background-color":a,display:!1===this.g.isVisible?"none":"","text-align":Uta[this.g.textAlign]};this.ka&&(b["border-radius"]=a?this.aa/
8+"px":"");g.fh(this.element,b);switch(this.g.Eg){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},Tta=function(a){var b=1+.25*(a.Ai||0);
if(a.offset==C7.Cu||a.offset==C7.Fu)b*=.8;return b},D7=function(a,b){var c={},d=b.background?b.background:a.g.jb.background,e;
if(null!=b.Je||b.background)e=null!=b.Je?b.Je:a.g.jb.Je,d=u7(d),c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")",a.ka&&(c["box-decoration-break"]="clone",c["border-radius"]=a.aa/8+"px");if(null!=b.Ai||null!=b.offset)c["font-size"]=a.J*Tta(b)+"px";d=1;e=b.color||a.g.jb.color;if(b.color||null!=b.gh)e=u7(e),d=null==b.gh?a.g.jb.gh:b.gh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.zh;f==g.e4.NONE&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";
b.tv&&(k=e=b.tv);var l=a.J/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1),d=[];switch(f){case g.e4.DROP_SHADOW:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case g.e4.RAISED:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case g.e4.DEPRESSED:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case g.e4.Ju:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case g.g4.lu:e=
'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case g.g4.qu:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case g.g4.ku:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case g.g4.CASUAL:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case g.g4.CURSIVE:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case g.g4.cp:e=g.$E()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case g.g4.Wt:case g.g4.Vo:e='Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.g.jb.offset);switch(e){case C7.Cu:c["vertical-align"]="sub";break;case C7.Fu:c["vertical-align"]="super"}b.fontFamily==g.g4.cp&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.sr&&(c["font-style"]="italic");b.Ns&&(c["text-decoration"]=
"underline");b.Gq&&(c.visibility="hidden");return c},Vta=function(a,b,c){a.H=a.H||!!c;
var d={};g.za(d,a.g.jb);g.za(d,c||b.o);g.za(d,a.pa.jb);c=a.F[0];var e;if(c&&d.background==c.background&&d.Je==c.Je&&!!d.Gq==!!c.Gq&&d.zh==c.zh){var f;for(f=0;f<a.F.length;f++)if(Rta(d,a.F[f])){e=a.G[f];break}if(!e){f={};for(var k in d)d[k]!=c[k]&&(f[k]=d[k]);e=g.re("SPAN");g.fh(e,D7(a,f));a.G[0].appendChild(e);f=1}a.G.length=f;a.F.length=f}else a.G.length=0,a.F.length=0,e=g.re("SPAN"),g.fh(e,D7(a,d)),a.A.appendChild(e);a.D&&a.D.parentNode!=e&&(g.ye(a.D),e.appendChild(a.D));c=(k=g.z(b.text))?b.text.split("\n"):
[b.text];for(f=0;f<c.length;f++){var l=c[f];if(0<f||0==a.B.length||!b.B){if(0<f||0!=a.B.length){var m=g.re("BR");e.appendChild(m)}e.appendChild(g.se("\u00a0"));a.D=g.se("\u00a0");e.appendChild(a.D)}l&&(m=a.D,m.parentNode&&m.parentNode.insertBefore(k?g.se(l):l,m))}a.F.push(d);a.G.push(e);a.B.push(b)},Wta=function(){},F7=function(a){this.F=a;
this.B=this.o=this.mode=this.A=0;this.C=new E7(this);this.D=new E7(this);this.g=[];this.clear()},Yta=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Ml:a,
Nl:b,result:0};a=Xta[a];b=Xta[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{Ml:a,Nl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Ml:a,Nl:b,result:2};return{Ml:a,Nl:b,result:3}},$ta=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,Zta(a.C,b,c,d))},aua=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?$ta(a,d.kv,d.lv,b):1==d.type&&a.A&496&&Zta(a.D,d.kv,d.lv,b)}a.g.length=0},G7=function(){this.g=0},H7=function(){this.o=this.A=this.g=0},I7=function(){this.timestamp=this.df=0;
this.g=!1},J7=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new I7}this.g=this.o=this.Gc=0;this.style=new G7;this.C=a;this.B=0},K7=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!=r.df){0==c&&(c=m,d=q);var n=String.fromCharCode(r.df),v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.df||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],r=q.df,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},fua=function(a,b){switch(a){case 0:return bua[(b&127)-32];
case 1:return cua[b&15];case 2:return dua[b&31];case 3:return eua[b&31]}return 0},L7=function(a){return a.A[a.Gc][a.o]},M7=function(a,b,c){2<=b&&1<a.o&&(--a.o,L7(a).df=0);
var d=L7(a);d.timestamp=a.C.o+0;d.df=fua(b,c);32>a.o&&a.o++},gua=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].jm(a.A[c+e][f])},N7=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},O7=function(a){a.Gc=0<a.g?a.g:1;
a.o=1;N7(a,0,15)},P7=function(a){this.B=a;
this.C=0;this.style=new G7;this.D=new J7(a);this.F=new J7(a);this.G=new J7(a);this.o=this.D;this.A=this.F;this.g=this.o},Q7=function(a,b,c){var d=a.o,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:K7(d,c),O7(a.o),O7(a.A),d.Gc=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;e?d.o=1:d.g!=b&&(d.g>b?(K7(d,c),N7(d,d.Gc-d.g,b)):d.Gc<b&&(b=d.g),d.g=b)},hua=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},iua=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.B.mode=1<<a.g.B},E7=function(a){this.o=a;
this.g=new H7;this.C=0;this.A=new P7(a);this.D=new P7(a);this.B=this.A},Zta=function(a,b,c,d){a.g.update();
b=Yta(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Ml;c=b.Nl;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),e=a.B.g,b&96&&M7(e,0,b),c&96&&M7(e,0,c),!a.o.F&&0!=b&&0!=c&&3==e.style.g&&K7(e,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&
14)>>1):0;c=b.g;switch(b.style.get()){case 4:d=c.Gc;break;case 3:if(d!=c.Gc){if(d<c.g&&(d=c.g,d==c.Gc))break;var f=1+c.Gc-c.g,k=1+d-c.g;gua(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));N7(c,b,e)}}c.Gc=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:M7(b.g,0,32);break a;case 48:57==c?(b=b.g,L7(b).df=0,32>b.o&&b.o++):M7(b.g,1,c&15)}break;case 2:c&32&&M7(b.g,2,c&31);break;case 3:c&32&&M7(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:hua(b);break;
case 33:b=b.g;1<b.o&&(--b.o,L7(b).df=0);break;case 36:b=b.g;d=L7(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:Q7(b,2,d);break;case 38:Q7(b,3,d);break;case 39:Q7(b,4,d);break;case 40:M7(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.G;d.g=15;d.style.set(4);O7(d);iua(b);break;case 43:iua(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:K7(a,d)}N7(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Gc){++a.Gc;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Gc<a.g&&(a.Gc=a.g));b=a.Gc-a.g+1;K7(a,d);gua(a,b,b+1,a.g-1);N7(a,a.Gc,1)}break;case 46:N7(b.A,0,15);break;case 47:K7(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;hua(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},R7=function(){},S7=function(a){this.A=a;
this.o=null},kua=function(a,b,c){var d=a.getAttribute("t"),d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0),e=a.getAttribute("d"),e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);
b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?T7.ip:T7.Al;a=g.Dr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");jua(d,e,k,b,f,a.firstChild,{},c)},jua=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.sr=!0;break;case "u":k.Ns=!0;break;case "font":var m=f.getAttribute("color");U7.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new v7(a,b,c,d,n.nodeValue,e||0<m,g.Tb(k)?void 0:k));else{var q={};g.za(q,k);jua(a,b,c,d,e||0<m,n,q,l)}}},V7=function(){this.A={};
this.o=null},W7=function(a){this.o={};
this.C={};this.D={};this.A="_"+x7++;this.B=a},X7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},Y7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},Z7=function(a,b){var c=X7(a,b);
if(void 0!=c)return c},$7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return U7.test(c),c},lua=function(a,b){var c={},d=b.getAttribute("ws");
g.za(c,d?a.D[d]:a.B);d=Z7(b,"mh");null!=d&&(c.zr=d);d=Z7(b,"ju");null!=d&&(c.textAlign=d);d=Z7(b,"pd");null!=d&&(c.vj=d);d=$7(b,"wfc");null!=d&&(c.windowColor=d);d=X7(b,"wfo");void 0!=d&&(c.Bj=d/255);return c},mua=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.za(c,a.C[d]);d=Z7(b,"ap");null!=d&&(c.Eg=d);d=X7(b,"cc");null!=d&&(c.Fv=d);d=X7(b,"ah");null!=d&&(c.Qh=d);d=X7(b,"rc");null!=d&&(c.Pn=d);d=X7(b,"av");null!=d&&(c.ai=d);return c},nua=function(a,b,c){var d={};
g.za(d,mua(a,b));g.za(d,lua(a,b));c?Rta(d,a.B)?(c=a.A,d=a.B):c="_"+x7++:c=b.getAttribute("id")||"0";a=X7(b,"t");b=X7(b,"d")||0x8000000000000;return new w7(a,b,0,c,d)},a8=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.o=new window.DataView(a);this.A=[]},b8=function(a){var b=a.g;
a.g+=1;return a.o.getUint8(b)},oua=function(a){var b=a.g;
a.g+=4;return a.o.getUint32(b)},c8=function(a,b){this.B=a;
this.o="CC3"==b.D?4:0;this.A=new F7(!1);this.A.A=1<<this.o},pua=function(a){if(!(a.g<a.o.byteLength))return!1;
var b=oua(a);b.toString(16);if(1380139777!=b)return!1;a.version=b8(a);if(1<a.version)return!1;b8(a);b8(a);b8(a);return!0},qua=function(){this.A=[];
this.g=[];this.o=-1},d8=function(a,b){return b?a.g.concat(a.A):a.g},e8=function(a,b){switch(b.B){case "asr":rua(b,a.A);
break;default:if(b.isDefault||0>a.o)a.o=a.g.length;rua(b,a.g)}},rua=function(a,b){g.$a(b,(0,g.A)(a.J,a))||b.push(a)},sua=function(a,b){var c=g.Ya(a.g,(0,g.A)(b.J,b));
-1!=c&&(a.o=c)},f8=function(){this.o=null},tua=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.sr=!0;break;case "u":l.Ns=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new v7(b,c,d,e.id,q.nodeValue,f||0<n,g.Tb(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var r={};g.za(r,l);tua(a,b,c,d,e,!0,q,r,m)}}},g8=function(a){var b=0;
a=g.ka(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+c.value;return 1E3*b},h8=function(a){this.zx=!!a;
this.g=new qua;this.D=[];this.o=null},vua=function(a){var b={};
if(a=s7(a))b.lang=a,uua.test(a)&&(b.vj=z7.Xo);return b},wua=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.z(b)){if("WEBVTT"==b.substring(0,6))return a.o||(a.o=new f8),a.o.g(b,d);b=g.Dr(b);if(!b||!b.firstChild)return[];a.o||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.o=new W7(vua(c)):a.o=new V7:a.o=new S7(vua(c)));return a.o.g(b,d)}try{var f;if(g.z(b))f=!1;else{var k=new a8(b,0,0);f=pua(k)}if(f)return a.o||(a.o=new c8(e,c)),a.o.g(b,d)}catch(l){g.BE(l)}return[]},xua=function(a,b){return g.$a(d8(a.g,!0),function(a){return a.toString()==
b})},i8=function(a){h8.call(this,a.Tl);
this.A=null;this.C=void 0;this.B=null;this.D=a.captionTranslationLanguages},j8=function(){this.kb=[]},k8=function(a,b,c,d,e,f){g.L.call(this);
this.J=a;this.G=b;this.B=new j8;this.g=null;this.D=d;this.H=f;this.o=this.A=null;this.L=c;this.C=e||!1;this.F=new g.Lt(this.Nx,1E3,this);g.M(this,this.F);b.addEventListener("seekto",this.Dr,this);this.Dr(b.getCurrentTime());this.Nx()},l8=function(a,b){h8.call(this);
this.C=a;this.W=b;this.A=null;this.B=!1},m8=function(a,b,c,d,e,f){B7.call(this,a,b,c,d,e,f);
this.type=A7.Ro},n8=function(a,b,c,d,e,f){B7.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=A7.Wo;this.L=this.S=0;this.M=window.NaN;this.na=null;this.ga=new g.Lt(this.sa,433,this);g.M(this,this.ga)},o8=function(a){if(!a.L){var b=g.re("SPAN");
g.fh(b,D7(a,a.g.jb));a.A.appendChild(b);b.appendChild(g.se("M"));var c=b.offsetHeight,d=g.re("BR");b.appendChild(d);b.appendChild(g.se("M"));a.L=b.offsetHeight-c;a.A.removeChild(b)}return a.L},p8=function(a,b,c,d){h8.call(this,d);
c=c||g.QE(a).hl||"";c=c.split("_").join("-");this.B=g.SE(a,{hl:c});this.C=b;this.F={};this.A=null},t8=function(a){g.OV.call(this,a);
g.cE();this.Y=g.Y(a);this.B=a.ha();this.fa=g.nV(a);this.W=a;var b=null,c=g.GD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.uD(c));this.ca=b;this.C={jb:{}};this.D={jb:{}};this.H=[];this.J={};this.N={};this.M=!1;this.ka="1"==this.B.Tb.cc_auto_caps||"1"==this.Y.J.cc_auto_caps;c=b=this.A=this.o=this.G=this.F=this.L=this.da=null;q8(this)||(b=new g.It(this.bB,void 0,this),g.M(this,b),c=new g.Lt(this.jP,2E3,this),g.M(this,c));this.S=b;this.ga=c;this.ba=new g.RL(this);g.M(this,this.ba);q8(this)||
this.ba.V(a,"resize",this.Ps);this.ba.V(a,"onPlaybackAudioChange",this.PK);this.ba.V(a,"crn_captions",this.XR,this);this.ba.V(a,"crx_captions",this.YR,this);r8(this,s8(this,"display-settings")||{});yua(this)&&this.load()},q8=function(a){return"3"!=a.Y.C?!1:!!a.W.app.F.g.textTracks},zua=function(a){var b;
a.B.captionTracks.length&&(b=a.g.gi().gv);if("FORCED_ON"==b||1==a.Y.Gg||1==a.B.Gg||"alwayson"==a.B.tf("yt:cc"))return!0;if(2==a.Y.Gg){var c=s8(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==a.B.tf("yt:cc")},yua=function(a){return q8(a)?!a.B.Ba:a.B.captionTracks.length&&a.g.gi().Vj?!0:zua(a)},Aua=function(a,b){if(!g.Y(a.g).experiments.g("legacy_default_captions"))return a.o?a.G&&a.G.ti?a.G.ti:d8(a.o.g,b||a.ka)[0]||u8(a):null;
var c=null;if(a.o){c=a.o.qw();!c&&b&&(c=d8(a.o.g,!0)[0]);if(!c&&(b||a.ka)){var d=a.o.g.A;d.length&&(c=xua(a.o,d[0].toString()))}c||(c=u8(a))}return c},u8=function(a){return g.Y(a.g).experiments.g("legacy_default_captions")?a.o.tw():a.G&&a.G.Vj},v8=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.M=c);a.A=b;a.load(d)},Bua=function(a,b){var c=g.xZ(a.fa,!0).height;
if(!c)return null;var d=a.fa.Xa();switch(null!=b.params.zr?b.params.zr:b.params.MP?A7.Wo:1<b.o.length?A7.Ro:A7.Uo){case A7.Ro:return new m8(b,a.C,a.D,c,d.width,d.height);case A7.Wo:return new n8(b,a.C,a.D,c,d.width,d.height);default:return new B7(b,a.C,a.D,c,d.width,d.height)}},r8=function(a,b,c){var d=w8.jb;
a.C={};g.za(a.C,w8);a.C.jb={};g.za(a.C.jb,d);a.D={jb:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;U7.test(f);e.jb.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;U7.test(f);e.jb.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||w8.windowColor;U7.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.Je);e.jb.Je=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;null==f&&(f=d.Ai);e.jb.Ai=f;e=b.textOpacityOverride?
a.D:a.C;f=b.textOpacity;null==f&&(f=d.gh);e.jb.gh=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=w8.Bj);e.Bj=f;e=b.charEdgeStyleOverride?a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.zh);e.jb.zh=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.jb.fontFamily=f;a.loaded&&a.Ps();c&&x8(a,"display-settings",b)},Dua=function(a,b){if(b&&!a.F){var c=y7({vj:z7.Oo,
lang:"cs"});a.F=[c,new v7(c.start,c.end-c.start,0,c.id,g.U("YTP_SAMPLE_SUBTITLES"))];g.yV(a.g,a.F)}else!b&&a.F&&(Cua(a,a.F),a.F=null)},Cua=function(a,b){g.AV(a.g,b);
(0,g.H)(b,function(a){g.jb(this.H,a)},a);
a.S.dk()},Eua=function(a,b){return a&&g.z(a)&&U7.test(a)?a:b},Fua=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Hua=function(a,b){if(a&&g.z(a)){var c=Gua.indexOf(a);
return-1!=c?c:b}return b},Jua=function(a,b){if(a&&g.z(a)){var c=Iua.indexOf(a);
return-1!=c?c:b}return b},Kua=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.Rd(a,-2,4):b},s8=function(a,b){if(!a.ca)return null;
var c;try{c=a.ca.get(b)}catch(d){a.ca.remove(b)}return c},x8=function(a,b,c){if(a.ca)try{a.ca.set(b,c)}catch(d){}};
g.GK.prototype.Jm=r7(2,function(a){return(a=g.HK(this,a))?a.g:0});
g.pN.prototype.Jm=r7(1,function(){return 0});
g.yI.prototype.J=r7(0,function(a){return a?this.toString()==a.toString():!1});
var Pta=/^#(?:[0-9a-f]{3}){1,2}$/i,Qta=/#(.)(.)(.)/,uua=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,C7={Cu:0,NORMAL:1,Fu:2},Iua="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),Gua=["none","raised","depressed","uniform","dropShadow"],U7=/^#(?:[0-9a-f]{3}){1,2}$/i;var y8={gu:0,SY:1,iD:2},Uta=["left","right","center"],z7={Oo:0,Xo:1,JZ:2,RT:3},T7={Z_:0,Al:5,ip:6},A7={Uo:0,Ro:1,Wo:2};var w8={windowColor:g.f4.Go,Bj:0,textAlign:y8.iD,Eg:7,Qh:50,ai:100,jb:{background:g.f4.Go,Je:.75,zh:g.e4.NONE,color:g.f4.mp,fontFamily:g.g4.Vo,Ai:0,gh:1,offset:C7.NORMAL}};g.p(v7,g.aT);v7.prototype.toString=function(){return g.aT.prototype.toString.call(this)};g.p(w7,g.aT);w7.prototype.toString=function(){return g.aT.prototype.toString.call(this)};
var x7=0;g.p(B7,g.X);g.h=B7.prototype;g.h.dJ=function(a,b){var c=g.uh(this.element,this.element.parentElement);this.ca=a-c.x;this.da=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.cJ=function(a,b){var c=g.xh(this.element),d=a-this.ca-.02*this.za,e=b-this.da-.02*this.va,f=(d+c.width/2)/this.N*3,f=Math.floor(g.Rd(f,0,2)),k=(e+c.height/2)/this.fa*3,k=Math.floor(g.Rd(k,0,2)),l=f+3*k,d=(d+f/2*c.width)/this.N,d=100*g.Rd(d,0,1),c=(e+k/2*c.height)/this.fa,c=100*g.Rd(c,0,1);this.C.params.Eg=l;this.C.params.ai=c;this.C.params.Qh=d;this.g.Eg=l;this.g.ai=c;this.g.Qh=d;this.qj(this.B)};
g.h.bJ=function(){g.eq(this.element,"ytp-dragging")};
g.h.Vb=function(){return this.type};
g.h.qj=function(a){var b=Math.min(this.uw(),this.N),c=this.rw();g.fh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"96%",height:c?c+"px":"96%",margin:"",transform:""});this.zp(a);a={transform:"",top:"",left:""};b||(a.width="");c||(a.height="");var d=.96*this.g.Qh+2,e=this.g.Eg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=
100-d+"%"}b=.96*this.g.ai+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.A.offsetHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.fh(this.element,a)};
g.h.zp=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.H||this.B.length>b)b=0,this.H=!1,this.B=[],this.F=[],this.G=[],this.D=null,g.ve(this.A);for(;b<a.length;b++)Vta(this,a[b])};
g.h.uw=function(){return 0};
g.h.rw=function(){return 0};
g.h.toString=function(){return g.X.prototype.toString.call(this)};Wta.prototype.B=function(){};F7.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
F7.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var Xta=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];G7.prototype.set=function(a){this.g=a};
G7.prototype.get=function(){return this.g};
H7.prototype.clear=function(){this.g=0};
H7.prototype.update=function(){this.g=2==this.g?1:0};
H7.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
I7.prototype.jm=function(a){this.df=a.df;this.timestamp=a.timestamp;this.g=a.g};
I7.prototype.reset=function(){this.timestamp=this.df=0;this.g=!1};
J7.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Gc=1};
var bua=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],cua=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],dua=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],eua=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];P7.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
E7.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};R7.prototype.reset=function(){};g.p(S7,R7);S7.prototype.g=function(a){var b=[];this.o||(this.o=y7(this.A),b.push(this.o));a=g.ka(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())kua(c.value,this.o.id,b);return b};g.p(V7,R7);
V7.prototype.g=function(a){var b=[];this.o||(this.o=y7(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=y7());
var k={};f&&(g.za(k,f.params),f=f.params.jb)&&(k.jb={},g.za(k.jb,f));e.getAttribute("rc")&&(k.Pn=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.Fv=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Eg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.Qh=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.ai=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.vj=z7.Xo,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.vj=z7.Oo));e.getAttribute("bc")&&(k.jb||(k.jb={}),k.jb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.jb||(k.jb={}),k.jb.Je=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.jb||(k.jb={}),k.jb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.MP=(0,window.parseInt)(e.getAttribute("sd"),10));
f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new w7(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],kua(a,this.o.id,d),d=g.ka(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(W7,R7);
W7.prototype.g=function(a){a.firstChild.getAttribute("format");var b,c;a=g.ka(a.firstChild.childNodes);for(var d=a.next();!d.done;d=a.next())switch(d=d.value,d.tagName){case "head":b=d;break;case "body":c=d}if(b)for(b=g.ka(b.childNodes),a=b.next();!a.done;a=b.next())switch(a=a.value,a.tagName){case "pen":var d=a.getAttribute("id"),e=this.o,f={},k=a.getAttribute("p");k&&g.za(f,this.o[k]);k=Y7(a,"b");null!=k&&(f.bold=k);k=Y7(a,"i");null!=k&&(f.sr=k);k=Y7(a,"u");null!=k&&(f.Ns=k);k=Z7(a,"et");null!=
k&&(f.zh=k);k=Z7(a,"of");null!=k&&(f.offset=k);k=$7(a,"bc");null!=k&&(f.background=k);k=$7(a,"ec");null!=k&&(f.tv=k);k=$7(a,"fc");null!=k&&(f.color=k);k=Z7(a,"fs");void 0!=k&&k!=g.g4.Wt&&(f.fontFamily=k);k=X7(a,"sz");void 0!=k&&(f.Ai=k/100-1);k=X7(a,"bo");void 0!=k&&(f.Je=k/255);a=X7(a,"fo");void 0!=a&&(f.gh=a/255);e[d]=f;break;case "ws":d=a.getAttribute("id");this.D[d]=lua(this,a);break;case "wp":d=a.getAttribute("id"),this.C[d]=mua(this,a)}b=[];if(c){a={};var d=void 0,l,m;c=g.ka(c.childNodes);for(e=
c.next();!e.done;e=c.next())switch(e=e.value,e.tagName){case "w":m=nua(this,e,!1);(e=a[m.id])&&e.end>m.start&&(e.end=m.start);a[m.id]=m;b.push(m);break;case "p":var n=d,q=l,f=[],k=e.getAttribute("w")||this.A,r=!!Y7(e,"a"),v=X7(e,"t")||0,x=X7(e,"d")||5E3;!q&&!r&&n&&n.windowId==k&&n.end>v&&(n.end=v);for(var n=r?T7.ip:T7.Al,q=this.o[e.getAttribute("p")],B=e.childNodes,F=0;F<B.length;F++){var O=B[F];0<F&&(r=!0);if("s"==O.tagName)var J=O,O=v,Za=x,lb=k,ia=r,sd=n,Bb=J.textContent?J.textContent:"",Qf=this.o[J.getAttribute("p")],
J=X7(J,"t")||0,O=new v7(O+J,Za-J,sd,lb,Bb,ia,Qf);else O=new v7(v,x,n,k,O.textContent||"",r,q);f.push(O)}d&&"\n"==d.text&&(d.text="");if(0<f.length)for(d=f[f.length-1],l=null!=e.getAttribute("d"),f[0].windowId==this.A&&(m=nua(this,e,!0),b.push(m)),e=g.ka(f),f=e.next();!f.done;f=e.next())f=f.value,f.windowId=m.id,m.o.push(f),b.push(f)}}return b};g.p(a8,Wta);a8.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+x7++;c=c/1E3-this.F;d=d/1E3-this.F;var k=T7.Al;a=new w7(c,d-c,k,f,{textAlign:y8.gu,Eg:0,Qh:2.5*b,ai:5.33*a});e=new v7(c,d-c,k,f,e);this.A.push(a);this.A.push(e)}};
g.p(c8,R7);c8.prototype.g=function(a){a=new a8(a,0,this.B);if(pua(a)){for(;a.g<a.o.byteLength;)for(0==a.version&&(a.D=oua(a)*(1E3/45)),a.C=b8(a);0<a.C;a.C--){var b=b8(a),c=b8(a),d=b8(a);b&4&&(b&3)==this.o&&(0==this.o||1==this.o)&&(b=this.A,b.g.push({time:a.D,type:this.o,kv:c,lv:d,order:b.g.length}))}aua(this.A,a);return a.A}return[]};
c8.prototype.reset=function(){this.A.clear()};g.p(f8,R7);
f8.prototype.g=function(a,b){for(var c=[],d=a.split(Lua),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Mua.test(f)){var l=z8.exec(f);if(l&&3<=l.length){var m=g8(l[1]),l=g8(l[2])-m,f=f.substring(z8.lastIndex);z8.lastIndex=0;var k=m+k,m=l,n=f,l={};this.o||(this.o=y7({zr:A7.Uo}),c.push(this.o));var q=this.o,f=T7.Al;if(0>n.indexOf("<"))c.push(new v7(k,m,f,q.id,n,!1,g.Tb(l)?void 0:l));else{n=n.split(Nua);1!=n.length&&(f=T7.ip,q="_"+Oua++,q=new w7(k,m,f,q,{}),c.push(q));for(var r=k,v=0;v<n.length;v++){var x=n[v];
if(0==v%2){var B=g.Dr("<html>"+x+"</html>"),F;B.getElementsByTagName("parsererror").length?(F=B.createElement("span"),F.appendChild(B.createTextNode(x))):F=B.firstChild;tua(this,r,m-(r-k),f,q,0<v,F,l,c)}else r=g8(x)}}}z8.lastIndex=0}}return c};
var Oua=0,Mua=/^NOTE/,Lua=/(?:\r\n|\r|\n){2,}/,z8=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),Nua=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.C(h8,g.L);g.h=h8.prototype;g.h.qw=function(a){var b=this.g.o,c=d8(this.g,!0);a&&0>b&&0<c.length&&(b=0);return 0>b?null:c[b]};
g.h.tw=function(){return null};
g.h.td=function(){this.o=null};
g.h.P=function(){h8.R.P.call(this);this.td()};
g.h.eA=function(){return!1};g.p(i8,h8);g.h=i8.prototype;g.h.vr=function(a,b,c){var d=this.bk(a),e=(0,g.A)(function(c){this.B=null;b(c.responseText,a)},this);
this.td();this.B=g.VE(d,{format:"RAW",Kb:e,withCredentials:!0});c&&this.A&&this.A.Vj!=a&&(this.A.ti=a)};
g.h.wr=function(a,b,c,d){this.C=c;if(this.A=d||null)for(b=g.ka(this.A.captionTracks),c=b.next();!c.done;c=b.next())e8(this.g,c.value);a()};
g.h.bk=function(a){var b=a.H,c={};if(this.C||a.A)c.fmt=this.C||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.SE(b,c)};
g.h.tw=function(){return this.A?this.A.Vj:null};
g.h.qw=function(){return this.A?this.A.ti:null};
g.h.td=function(){h8.prototype.td.call(this);this.B&&this.B.abort()};
g.h.P=function(){this.td();h8.prototype.P.call(this)};j8.prototype.contains=function(a){a=g.vb(this.kb,a);return 0<=a||0>a&&1==(-a-1)%2};
j8.prototype.length=function(){return this.kb.length/2};g.p(k8,g.L);g.h=k8.prototype;g.h.P=function(){g.L.prototype.P.call(this);this.G.removeEventListener("seekto",this.Dr,this);this.o&&this.o.abort()};
g.h.Dr=function(a){var b=this.g;this.g=g.Xa(this.L.Mg(a).g);b!=this.g&&this.H&&this.H()};
g.h.reset=function(){this.B=new j8;this.o&&(this.o.abort(),this.o=null)};
g.h.Nx=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Sh(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.G.getCurrentTime())){a=this.g;a=a.g.rk(a);if(!this.B.contains(a.g[0].Na)){var b=g.XM(g.bN(a,this.J,{})),c={format:"RAW",sd:(0,g.A)(this.yN,this),withCredentials:!0};this.C&&(c.responseType="arraybuffer");this.o=g.VE(b,c);this.A=a;var b=this.B,c=this.A.g[0].Na,d=g.vb(b.kb,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.kb[d-1]&&d<b.kb.length&&1==b.kb[d]-c?(g.ib(b.kb,d),g.ib(b.kb,d-1)):0<
d&&1==c-b.kb[d-1]?b.kb[d-1]=c:d<b.kb.length&&1==b.kb[d]-c?b.kb[d]=c:(g.rb(b.kb,d,0,c),g.rb(b.kb,d+1,0,c)))}this.g=g.Xa(a.g)}this.F.start()};
g.h.yN=function(a){(this.C?!a.response:!a.responseText)||400<=a.status||null===this.D||(this.C?this.D(a.response,1E3*this.A.g[0].startTime):this.D(a.responseText,1E3*this.A.g[0].startTime));this.o=this.A=null};g.p(l8,h8);g.h=l8.prototype;g.h.vr=function(a,b){this.td();var c=this.C.g[a.o];if(c){var d=1E3*c.index.Jm(c.index.Ei()),e=g.Y(this.W).Rc;this.A=new k8(new g.bM,this.W,c,function(c,e){b(c,a,e,d)},e,(0,g.A)(function(){e&&(this.A&&this.A.reset(),this.o&&this.o.reset(),this.B=!0)},this))}};
g.h.eA=function(){var a=this.B;this.B=!1;return a};
g.h.wr=function(a){g.Y(this.W).Rc?(e8(this.g,new g.yI({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),e8(this.g,new g.yI({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):e8(this.g,new g.yI({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.td=function(){h8.prototype.td.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.bk=function(){return""};
g.h.P=function(){this.td();h8.prototype.P.call(this)};g.p(m8,B7);m8.prototype.zp=function(a){var b=this.C.o;B7.prototype.zp.call(this,a);var c,d;for(a=a.length;a<b.length;a++){var e=b[a],f;d&&e.o==c?f=d:(f={},g.za(f,e.o),g.za(f,Pua),c=e.o,d=f);Vta(this,e,f)}};
var Pua={Gq:!0};g.p(n8,B7);n8.prototype.sa=function(){g.eq(this.element,"ytp-rollup-mode");this.qj(this.na,!0)};
n8.prototype.uw=function(){var a=this.C.params.Fv;if(!this.S&&a){var b=g.re("SPAN");g.He(b,"\u00a0"+(0,g.La)("\u2014",a)+"\u00a0");g.fh(b,D7(this,this.g.jb));this.A.appendChild(b);this.S=b.offsetWidth;this.A.removeChild(b)}return this.S};
n8.prototype.rw=function(){return this.C.params.Pn*o8(this)};
n8.prototype.qj=function(a,b){this.na=a;if(o8(this)){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));c=1;for(d=0;d<a.length;d++){var e=a[d];g.z(e.text)&&(c+=e.text.split("\n").length-1,e.B||0==d||c++)}c=this.C.params.Pn-c;c!=this.M&&(b||(0,window.isNaN)(this.M)||(g.S(this.element,"ytp-rollup-mode"),this.ga.Pe()),d="",c&&(d="translateY("+Math.ceil(c*o8(this))+"px)"),g.fh(this.A,"transform",d),this.M=c);B7.prototype.qj.call(this,a)}else B7.prototype.qj.call(this,
a)};g.C(p8,h8);g.h=p8.prototype;g.h.vr=function(a,b){var c=this.bk(a),d=(0,g.A)(function(c){this.A=null;b(c.responseText,a)},this);
this.td();this.A=g.VE(c,{format:"RAW",Kb:d,withCredentials:!0});sua(this.g,a)};
g.h.wr=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.C,fmts:Number(b||!1),vssids:1};this.zx&&(b.asrs=1);d=g.SE(d,b);b=(0,g.A)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.g,e=g.ka(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value,l=m.getAttribute("formats"),n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),v=m.getAttribute("kind"),x=m.getAttribute("id"),B="true"==m.getAttribute("lang_default"),
F="true"==m.getAttribute("cantran"),m=m.getAttribute("vss_id");e8(d,new g.yI({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:v,id:x,is_servable:!0,is_default:B,is_translateable:F,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),v="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:q,id:r,
is_default:v},this.F[l.languageCode]=l.languageName,this.D.push(new g.xI(l))}a()},this);
this.td();this.A=g.VE(d,{format:"RAW",Kb:b,withCredentials:!0})};
g.h.bk=function(a){var b=this.B,c={v:this.C,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=s7(a));return b=g.SE(b,c)};
g.h.td=function(){p8.R.td.call(this);this.A&&this.A.abort()};
g.h.P=function(){this.td();p8.R.P.call(this)};g.C(t8,g.OV);g.h=t8.prototype;g.h.P=function(){q8(this)||Dua(this,!1);t8.R.P.call(this)};
g.h.load=function(a){t8.R.load.call(this);this.G=this.g.gi();if(this.o||a)this.A?(a?this.Oz(a,this.A):3!=this.g.Za()&&this.o.vr(this.A,(0,g.A)(this.Oz,this),g.Y(this.g).experiments.g("legacy_default_captions")),this.g.ya("captionschanged",t7(this.A))):this.g.ya("onCaptionsTrackListChanged");else{var b;a=this.B;a.Ba||g.Y(this.W).Rc&&null!=a.ua&&null!=a.ua.g.rawcc?b=new l8(this.B.ua,this.g):this.B.captionTracks.length?b=new i8(this.B):b=new p8(this.B.Ul,this.B.videoId,this.B.ri||this.Y.ri||this.B.tf("yt:cc_default_lang")||
this.Y.pa,this.B.Tl);this.o=b;b.wr((0,g.A)(this.eO,this),!0,q8(this)?"vtt":void 0,this.g.gi())}};
g.h.unload=function(){if(q8(this))for(var a=g.ee("track",void 0,this.fa.g),b=0;b<a.length;b++)g.ye(a[b]);else g.Nt(this.ga),g.BV(this.g,"captions"),this.H=[],this.o&&this.o.td(),this.F&&g.yV(this.g,this.F),this.Ps();t8.R.unload.call(this);(a=g.lV(this.g.app))&&a.C&&g.DJ(a.C.A);this.g.ya("captionschanged",{})};
g.h.eO=function(){var a;if(this.M||zua(this))a=Aua(this,this.M);if(q8(this))for(var b=d8(this.o.g,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.zI(d),srclang:s7(d),src:this.o.bk(d)};d==a&&(e["default"]=1);for(var d=this.W.app.F,e=[g.pe("TRACK",e)],f=0;f<e.length;f++)d.g.appendChild(e[f])}else!this.A&&a&&v8(this,a),this.g.ya("onCaptionsTrackListChanged"),this.g.ya("onApiChange")};
g.h.WP=function(){this.loaded&&!q8(this)&&this.unload()};
g.h.Oz=function(a,b,c,d){if(a){this.o.eA()&&(this.H=[],g.BV(this.W,"captions"),this.S.dk());a=wua(this.o,a,b,c,d);c={trackName:b.C,trackKind:b.B,trackLangCode:s7(b)};b.g&&(c.fromLangCode=b.o);g.sV(this.g,"cc",c);if(this.A!=u8(this)){if(this.M&&!g.cM(this.Y)&&!g.IO(this.Y)){g.Nt(this.ga);b=y7({Eg:0,Qh:5,ai:5,Pn:2,textAlign:y8.gu,vj:z7.Oo,lang:"cs"});this.L=[b];c=g.U("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.da||(d=new g.kR(g.tE()),g.M(this,d),this.da=d.element);d=b.end-b.start;var e=g.zI(this.A);
e&&this.L.push(new v7(b.start,d,0,b.id,e));this.L.push(new v7(b.start,d,0,b.id,c[0]),new v7(b.start,d,0,b.id,this.da,!0),new v7(b.start,d,0,b.id,c[1],!0));g.yV(this.g,this.L);this.ga.Pe()}if(this.M||g.cM(this.Y))x8(this,"module-enabled",!0),!g.Y(this.g).experiments.g("legacy_default_captions")&&this.G&&(this.G.ti=this.A);(b=g.lV(this.g.app))&&b.C&&g.DJ(b.C.A)}g.yV(this.g,a);this.M=!1}};
g.h.XR=function(a){this.H.push(a);this.S.dk()};
g.h.YR=function(a){g.jb(this.H,a);this.S.dk()};
g.h.XO=function(a){if(a instanceof w7){var b=this.J[a.id];b&&b.C!=a&&(b.dispose(),delete this.J[a.id],b=null);b||(b=Bua(this,a))&&(this.J[a.id]=b)}else b=a.windowId,this.N[b]||(this.N[b]=[]),this.N[b].push(a)};
g.h.jP=function(){Cua(this,this.L);this.L=null};
g.h.bB=function(){this.S.stop();Sta(this.N);this.H.sort(g.bT);(0,g.H)(this.H,this.XO,this);g.Ib(this.J,function(a,b){!this.N[b]||this.F&&-1==this.F.indexOf(a.C)?(a.dispose(),delete this.J[b]):(a.element.parentNode||g.DV(this.g,a.element,5),a.qj(this.N[b]))},this)};
g.h.pA=function(){r8(this,{},!0)};
g.h.oq=function(){var a=w8.jb,a={background:a.background,backgroundOpacity:a.Je,charEdgeStyle:a.zh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.Ai,textOpacity:a.gh,windowColor:w8.windowColor,windowOpacity:w8.Bj},b=s8(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Ss=function(a,b){var c={};g.za(c,s8(this,"display-settings"));g.za(c,a);r8(this,c,b);this.g.U("captionssettingschanged")};
g.h.Ps=function(){!q8(this)&&this.loaded&&(g.Ib(this.J,function(a,b){a.dispose();delete this.J[b]},this),this.bB())};
g.h.WB=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Rd(b,-2,4);this.Ss({fontSizeIncrement:c});return c;case "reload":b&&!q8(this)&&v8(this,this.A,!0);break;case "stickyLoading":void 0!=b&&this.Y.Fb&&x8(this,"module-enabled",!!b);break;case "track":if(!this.o)return{};if(b){if(q8(this))break;if(!g.va(b))break;if(g.Tb(b)){v8(this,null,!0);break}for(var d,e=d8(this.o.g,!0),c=0;c<e.length;c++){var f=e[c];f.o!=b.languageCode||d&&f.D!=b.languageName||(d=b.translationLanguage?
Ota(f,b.translationLanguage):f)}!d||d==this.A&&this.loaded||v8(this,d,!0)}else return this.loaded&&this.A&&this.A!=u8(this)?t7(this.A):{};return"";case "tracklist":return this.o?(0,g.I)(d8(this.o.g,b&&b.includeAsr),function(a){return t7(a)}):[];
case "translationLanguages":return this.o?this.o.D:[];case "displaySettings":d=this.oq();if(g.cM(this.Y)&&b&&g.va(b))if(b.reset)this.pA();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=Eua(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=Fua(b[c],d[c]);break;case "charEdgeStyle":f[c]=Hua(b[c],d[c]);break;case "fontSizeIncrement":f[c]=Kua(b[c],d[c]);break;case "fontFamilyOption":f.fontFamily=Jua(b[c],d[c])}for(e in f)f[e+
"Override"]=!0;this.Ss(f,!0);d=this.oq()}d.fontFamilyOption=Iua[d.fontFamily];d.charEdgeStyle=Gua[d.charEdgeStyle];return d;case "sampleSubtitles":q8(this)||void 0==b||Dua(this,!!b);break;case "xmlTrack":b&&this.Y.Fb&&!q8(this)&&v8(this,new g.yI({languageName:b.name}),!1,b.xml)}};
g.h.VR=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.Y.Fb&&a.push("stickyLoading","xmlTrack");return a};
g.h.WR=function(){var a=this.A;return a?{cc:a.F}:{}};
g.h.ZA=function(){this.loaded&&this.A?(x8(this,"module-enabled",!1),this.unload()):v8(this,this.A||Aua(this,!0),!0)};
g.h.PK=function(){this.B.captionTracks.length&&(this.loaded&&this.unload(),yua(this)&&this.load())};window._exportCheck==g.Aa&&g.u("ytmod.player.captions",t8,void 0);})(_yt_player);
