(function(g){var window=this;var Qua=function(a,b,c,d){var e=b.ac();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.Ub(c,d?d:"mqdefault.jpg");var k=b instanceof g.rQ?g.UV(b.lengthSeconds):null,l=!!f,f=l&&"RD"==g.TP(f).type,m=b instanceof g.rQ?b.Ba:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.U("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Mm(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.SQ&&(c.playlist_length=b.getLength());a.update(c)},A8=function(a,b){g.TV.call(this,{K:"div",
ea:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.g=a;this.N=!1},B8=function(a){g.XZ.call(this,a,{K:"div",
ea:["ytp-thumbnail-overlay","ytp-channel-overlay"],O:[{K:"div",X:"ytp-thumbnail-overlay-image",Z:{style:"{{background}}"}},{K:"div",X:"ytp-thumbnail-overlay-curtain"}]})},C8=function(a){var b={K:"div",
X:"ytp-upnext",Z:{"aria-label":"{{watch}}"},O:[{K:"div",X:"ytp-thumbnail-overlay-image",Z:{style:"{{background}}"}},{K:"div",X:"ytp-thumbnail-overlay-curtain"},{K:"span",X:"ytp-upnext-top",O:[{K:"span",X:"ytp-upnext-header",O:[g.U("YTP_PLAYLIST_UP_NEXT")]},{K:"span",X:"ytp-upnext-title",O:["{{title}}"]},{K:"span",X:"ytp-upnext-author",O:["{{author}}"]}]},{K:"a",X:"ytp-upnext-autoplay-icon",Z:{href:"{{url}}","aria-label":g.U("YTP_AUTOPLAY_NEXT")},O:[{K:"svg",Z:{height:"100%",version:"1.1",viewBox:"0 0 98 98",
width:"100%"},O:[{K:"circle",X:"ytp-svg-autoplay-circle",Z:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{K:"circle",X:"ytp-svg-autoplay-ring",Z:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{K:"polygon",X:"ytp-svg-autoplay-triangle",Z:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{K:"span",X:"ytp-upnext-bottom",O:[{K:"span",X:"ytp-upnext-cancel"},{K:"span",X:"ytp-upnext-paused",
O:[g.U("YTP_AUTOPLAY_PAUSED_3")]}]},{K:"span",X:"ytp-upnext-close"}]};g.X.call(this,b);this.B=null;var c=this.wa["ytp-upnext-cancel"],b=this.wa["ytp-upnext-close"];this.B=new g.X({K:"button",ea:["ytp-upnext-cancel-button","ytp-button"],Z:{tabindex:0,"aria-label":g.U("YTP_AUTOPLAY_CANCEL")},O:[g.U("YTP_CANCEL")]});g.M(this,this.B);this.B.T("click",this.hz,this);this.B.Ha(c);c=new g.X({K:"button",ea:["ytp-upnext-close-button","ytp-button"],Z:{"aria-label":g.U("YTP_AUTOPLAY_CANCEL")}});g.M(this,c);c.T("click",
this.hz,this);c.Ha(b);this.g=a;this.J=this.wa["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.Lt(this.dm,5E3,this);g.M(this,this.G);this.H=0;this.V(this.wa["ytp-upnext-autoplay-icon"],"click",this.ZM);this.ez();this.V(a,"autonavvisibility",this.ez);this.V(a,"mdxnowautoplaying",this.mM);this.V(a,"mdxautoplaycanceled",this.nM);this.V(a,"mdxautoplayupnext",this.eB);3==this.g.Za()&&(a=(a=g.kV(g.fV(this.g)))?a.hG():null)&&this.eB(a)},Rua=function(a,b){a.C=b;
Qua(a,b,g.Y(a.g),"hqdefault.jpg")},D8=function(a,b){a.A||(g.qG("a11y-announce",g.U("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.H=(0,g.CG)(),a.A=new g.Lt((0,g.A)(a.wp,a,b),25),a.wp(b));
g.eq(a.element,"ytp-upnext-autoplay-paused")},F8=function(a){E8(a);
a.H=(0,g.CG)();a.wp();g.S(a.element,"ytp-upnext-autoplay-paused")},E8=function(a){a.A&&(a.A.dispose(),a.A=null)},G8=function(a){A8.call(this,a,"subscribecard-endscreen");
var b=a.ha();this.A=new B8(a);g.M(this,this.A);g.DV(this.g,this.A.element,5);this.B=new g.X(["div","ytp-subscribe-card",["img","ytp-author-image",{src:b.profilePicture}],["div","ytp-subscribe-card-right",["div","ytp-author-name",b.author],["div","html5-subscribe-button-container"]]]);g.M(this,this.B);this.B.Ha(this.element);this.C=new g.J1(g.U("YTP_SUBSCRIBE"),null,g.U("YTP_UNSUBSCRIBE"),null,!0,!1,b.Qk,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.C);this.C.Ha(this.B.wa["html5-subscribe-button-container"]);
this.oa()},H8=function(a){var b=g.Y(a),b=b.A&&!b.D;
g.X.call(this,{K:"a",X:"ytp-videowall-still",Z:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},O:[{K:"div",X:"ytp-videowall-still-image",Z:{style:"{{background}}"}},{K:"span",X:"ytp-videowall-still-info",O:[{K:"span",X:"ytp-videowall-still-info-bg",O:[{K:"span",X:"ytp-videowall-still-info-content",Z:g.eF||g.Xe?{style:"will-change: opacity"}:void 0,O:[{K:"span",X:"ytp-videowall-still-info-title",O:["{{title}}"]},
{K:"span",X:"ytp-videowall-still-info-author",O:["{{author_and_views}}"]},{K:"span",X:"ytp-videowall-still-info-live",O:[g.U("YTP_LIVE")]},{K:"span",X:"ytp-videowall-still-info-duration",O:["{{duration}}"]}]}]}]},{K:"span",ea:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],O:[{K:"span",X:"ytp-videowall-still-listlabel-icon"},g.U("YTP_PLAYLIST"),{K:"span",X:"ytp-videowall-still-listlabel-length",O:[" (",{K:"span",O:["{{playlist_length}}"]},")"]}]},{K:"span",ea:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],O:[{K:"span",X:"ytp-videowall-still-listlabel-mix-icon"},g.U("YTP_MIX"),{K:"span",X:"ytp-videowall-still-listlabel-length",O:[" (50+)"]}]}]});this.B=b;this.g=a;this.A=null;this.T("click",this.C);this.T("keypress",this.D);g.Y(a).experiments.g("player_interaction_logging")&&(a=a.app.ba,g.gb(a.A,this),b=String(a.G++),this.element.setAttribute("data-visual-id",b),g.Se(this,(0,g.A)(a.F,a,this)))},I8=function(a,b){A8.call(this,a,"videowall-endscreen");
this.ca=a;this.da=b;this.G=0;this.A=[];this.H=this.D=this.C=null;this.J=this.S=!1;this.F=new g.RL(this);g.M(this,this.F);this.L=new g.Lt(g.ya(g.S,this.element,"ytp-show-tiles"),0);g.M(this,this.L);var c=new g.X({K:"button",ea:["ytp-button","ytp-endscreen-previous"],Z:{"aria-label":g.U("YTP_PREVIOUS")},O:[g.fE()]});g.M(this,c);c.Ha(this.element);c.T("click",this.gS,this);this.M=new g.kR({K:"div",X:"ytp-endscreen-content"});g.M(this,this.M);this.M.Ha(this.element);c=new g.X({K:"button",ea:["ytp-button",
"ytp-endscreen-next"],Z:{"aria-label":g.U("YTP_NEXT")},O:[g.gE()]});g.M(this,c);c.Ha(this.element);c.T("click",this.fS,this);this.B=new C8(a);g.M(this,this.B);g.DV(this.g,this.B.element,5);this.oa()},J8=function(a){return g.EV(a.g)&&a.Bp()&&!a.H},Sua=function(a){return(0,g.I)(a.Pf,function(a){return g.PZ(a)})},Tua=function(a,b,c){return 0==b&&a.C.length&&(b=c/I8.g,2<=c/I8.g&&2<=b&&g.Y(a.g).experiments.g("video_wall_emphasize_first"))?2*I8.g:I8.g},K8=function(a){var b=a.Ht();
b!=a.S&&(a.S=b,a.g.U("autonavvisibility"))},L8=function(a){g.OV.call(this,a);
g.bE({});this.o=null;this.isAvailable=!0;this.A=new g.RL(this);g.M(this,this.A);this.B=g.Y(a);Uua(a)?this.o=new I8(this.g,this):this.B.Pa?this.o=new G8(this.g):this.o=new A8(this.g);g.M(this,this.o);g.DV(this.g,this.o.element,5);this.oA();this.A.V(a,"videodatachange",this.oA,this);this.A.V(a,"crn_endscreen",this.JR,this);this.A.V(a,"crx_endscreen",this.KR,this)},Uua=function(a){a=g.Y(a);
return a.Yb&&!a.Pa};g.C(A8,g.TV);A8.prototype.create=function(){this.N=!0};
A8.prototype.destroy=function(){this.N=!1};
A8.prototype.Bp=function(){return!1};
A8.prototype.Ht=function(){return!1};g.p(B8,g.XZ);B8.prototype.Ib=function(a){a?this.A.show():g.aW(this.A)};g.p(C8,g.X);g.h=C8.prototype;g.h.dm=function(){this.D&&(this.G.stop(),this.Fa(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.ez=function(){this.Ib(g.gV(this.g))};
g.h.OM=function(){window.focus();this.dm()};
g.h.oa=function(){g.X.prototype.oa.call(this)};
g.h.wp=function(a){a=a||g.Y(this.g).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.CG)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.g.Za()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;var b=g.Y(this.g);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.sV(this.g,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.ac(),this.dm(),this.D=new window.Notification(g.U("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.Ub(b)}),this.F=this.V(this.D,"click",this.OM),this.G.start())}E8(this);
this.g.Fj(!1,a)};
g.h.ZM=function(a){!g.Fe(this.B.element,g.PF(a))&&g.cW(a,this.g)&&this.select()};
g.h.hz=function(){g.tV(this.g,"autonavcancel");g.iV(this.g,!0)};
g.h.mM=function(a){this.g.Za();this.show();D8(this,a)};
g.h.eB=function(a){this.g.Za();this.C&&this.C.ac().videoId==a.ac().videoId||Rua(this,a)};
g.h.nM=function(){this.g.Za();E8(this);this.oa()};
g.h.P=function(){E8(this);this.dm();g.X.prototype.P.call(this)};g.C(G8,A8);G8.prototype.show=function(){G8.R.show.call(this);this.A.Ib(!0)};
G8.prototype.oa=function(){G8.R.oa.call(this);this.A.Ib(!1)};g.p(H8,g.X);H8.prototype.mj=function(){var a=this.A.ac().videoId,b=this.A.getPlaylistId();g.P2(this.g.app,a,this.A.Gd,b,void 0,void 0)};
H8.prototype.C=function(a){g.HV(this.g,this);var b=(g.Y(this.g).experiments.g("web_player_endscreen_new_tab")||!this.g.isFullscreen())&&this.B;g.cW(a,this.g,b,this.A.Gd||void 0)&&this.mj()};
H8.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.UF(a)||(this.mj(),g.WF(a))}};g.C(I8,A8);I8.g=2;g.h=I8.prototype;g.h.create=function(){I8.R.create.call(this);var a=this.g.ha();a&&(this.C=Sua(a),this.D=a);this.mh();this.F.V(this.g,"appresize",this.mh);this.F.V(this.g,"videodatachange",this.hS);this.F.V(this.g,"autonavchange",this.ZB);this.F.V(this.g,"autonavcancel",this.eS);this.F.V(this.element,"transitionend",this.fO)};
g.h.destroy=function(){g.TL(this.F);g.Ue(this.A);this.A=[];this.C=null;I8.R.destroy.call(this);g.eq(this.element,"ytp-show-tiles");this.L.stop()};
g.h.Bp=function(){return 1!=this.D.autonavState};
g.h.show=function(){I8.R.show.call(this);g.eq(this.element,"ytp-show-tiles");g.Y(this.g).isMobile?g.Mt(this.L):this.L.start();(this.J||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.iV(this.g,!1);var a=J8(this);g.EV(this.g)&&g.Y(this.g).experiments.g("ui_logging")&&this.da.log({cancelButtonShow:a?"1":"0",state:this.Bp()?"enabled":"disabled"});a?(K8(this),2==this.D.autonavState?g.Y(this.g).experiments.g("fast_autonav_in_background")&&3==this.g.zo()?this.B.select(!0):D8(this.B):3==this.D.autonavState&&
F8(this.B)):(g.iV(this.g,!0),K8(this))};
g.h.oa=function(){I8.R.oa.call(this);F8(this.B);K8(this)};
g.h.fO=function(a){g.PF(a)==this.element&&this.mh()};
g.h.mh=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.xh(this.element),b=a.width/a.height,c=96/54,d=I8.g,e=I8.g,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(I8.g,2),n,q=Tua(this,0,k),r=Tua(this,1,k);n=l*m+(Math.pow(q,2)-m);n+=Math.pow(r,2)-m;for(n-=m;0<n&&(d<f||e<k);){var v=d/I8.g,x=e/I8.g,B=d<=f-I8.g&&n>=x*m,F=e<=k-I8.g&&n>=v*m;if((v+1)/x*c/b>b/(v/(x+1)*c)&&F)n-=v*m,e+=I8.g;else if(B)n-=x*m,d+=I8.g;else if(F)n-=v*m,e+=I8.g;
else break}c=!1;f=I8.g+q;n>=3*m&&6>=l*m-n&&(e>=f||d>=f)&&r<=I8.g&&(c=!0);n=96*d;m=54*e;b=n/m<b?a.height/m:a.width/n;b=Math.min(b,2);n*=b;m*=b;n*=g.Rd(a.width/n||1,1,1.21);m*=g.Rd(a.height/m||1,1,1.21);n=Math.floor(Math.min(a.width,n));m=Math.floor(Math.min(a.height,m));a=this.M.element;g.wh(a,n,m);g.fh(a,{marginLeft:n/-2+"px",marginTop:m/-2+"px"});Rua(this.B,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",J8(this));K8(this);b=n+4;n=m+4;m=0;f=!1;for(k=0;k<d;k++)for(v=0;v<e;v++)if(x=r>I8.g&&1<=
m&&!f?m+1:m,F=0,c&&k>=d-I8.g&&v>=e-I8.g?F=1:0==v%I8.g&&0==k%I8.g&&(v<q&&k<q?0==v&&0==k&&(F=q):r>I8.g&&v>=e-r&&k>=d-r?v==e-r&&k==d-r&&(f=!0,x=1,F=r):F=I8.g),x=g.Sd(x+this.G,l),0!=F){B=this.A[m];B||(B=new H8(this.g),this.A[m]=B,a.appendChild(B.element));var O=Math.floor(n*v/e),J=Math.floor(b*k/d),Za=Math.floor(n*(v+F)/e)-O-4,lb=Math.floor(b*(k+F)/d)-J-4;g.lh(B.element,J,O);g.wh(B.element,lb,Za);g.fh(B.element,"transitionDelay",(v+k)/20+"s");g.T(B.element,"ytp-videowall-still-mini",1==F);g.T(B.element,
"ytp-videowall-still-large",2<F);x=this.C[x];B.A=x;Qua(B,x,g.Y(B.g),g.cq(B.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");F=x.Gd;x=B.g;g.Y(x).experiments.g("player_interaction_logging")&&(x=x.app.ba,F=F&&F.itct,B=B.element.getAttribute("data-visual-id"),g.FV(x,"onLogServerVeCreated",{id:B,tracking_params:F}));m++}g.T(this.element,"ytp-endscreen-paginate",m<l);for(d=this.A.length-1;d>=m;d--)B=this.A[d],g.ye(B.element),g.Te(B);this.A.length=m}};
I8.A=2;I8.o=1.21;g.h=I8.prototype;g.h.hS=function(){var a=this.g.ha();this.D!=a&&(this.G=0,this.C=Sua(a),this.D=a,this.mh())};
g.h.fS=function(){this.G+=this.A.length;this.mh()};
g.h.gS=function(){this.G-=this.A.length;this.mh()};
g.h.nI=function(){return!!this.B.A};
g.h.ZB=function(a){1==a?(this.J=!1,this.H=this.D.clientPlaybackNonce,E8(this.B),this.o&&this.mh()):(this.J=!0,this.o&&J8(this)&&(2==a?D8(this.B):3==a&&F8(this.B)))};
g.h.eS=function(a){if(a){for(a=0;a<this.A.length;a++)g.IV(this.ca,this.A[a],!0);this.ZB(1)}else this.H=null,this.J=!1;this.mh()};
g.h.Ht=function(){return this.o&&J8(this)};g.C(L8,g.OV);g.h=L8.prototype;g.h.UB=function(){var a=this.g.ha(),b=!Uua(this.g)||!(!a.Pf||!a.Pf.length),a=g.LQ(a,"ypc_module"),c=g.ZZ(this.g.app);return(b||!1)&&!a&&!c};
g.h.TB=function(){return this.o.Ht()};
g.h.lI=function(){return this.TB()?this.o.nI():!1};
g.h.P=function(){g.BV(this.g,"endscreen");L8.R.P.call(this)};
g.h.load=function(){L8.R.load.call(this);this.o.show();g.Y(this.g).Pa&&.01>Math.random()&&this.log({trailerEndscreenShow:1})};
g.h.log=function(a){g.sV(this.g,"end",a)};
g.h.unload=function(){L8.R.unload.call(this);this.o.oa();this.o.destroy();this.isAvailable=!1};
g.h.JR=function(a){this.UB()&&(this.o.N||this.o.create(),"load"==a.getId()&&this.load())};
g.h.KR=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.oA=function(){g.BV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ha().lengthSeconds-10),0),a=new g.aT(a,0x8000000000000,{id:"preload",namespace:"endscreen"}),b=new g.aT(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.yV(this.g,[a,b])};window._exportCheck==g.Aa&&g.u("ytmod.player.endscreen",L8,void 0);})(_yt_player);
