(function(g){var window=this;var p$=function(a){for(var b;0<a.A.length;)b=a.A.pop(),b.disconnect();a.o&&a.o.disconnect()},q$=function(a){return!g.z((0,g.l4)())&&(0,g.l4)().createMediaElementSource&&!!a.g},Rwa=function(a,b){q$(a);
var c=(0,g.l4)().createChannelMerger(b);a.A.push(c);return c},Swa=function(a,b){q$(a);
var c=(0,g.l4)().createChannelSplitter(b);a.A.push(c);return c},r$=function(a){q$(a);
var b=(0,g.l4)().createGain();a.A.push(b);return b},s$=function(a){q$(a);
if(!a.o){var b=a.g;a.o=(0,g.l4)().createMediaElementSource(b.ra())}return a.o},t$=function(a){q$(a);
return(0,g.l4)().destination},u$=function(a){this.o=null;
this.A=[];this.B=!1;this.g=null;this.W=a},v$=function(a,b){var c=g.fV(a).B;
c&&c.YB(b)},w$=function(a){this.length=a.length||a;
for(var b=0;b<this.length;b++)this[b]=a[b]||0},x$=function(a){this.length=a.length||a;
for(var b=0;b<this.length;b++)this[b]=a[b]||0},y$=function(a){var b=a[0],c=a[1];
a=a[2];return Math.sqrt(b*b+c*c+a*a)},A$=function(a,b,c,d,e,f,k){this.C=f;
this.D=Math.cos(k);this.F=Math.sin(k);this.g=r$(a);this.o=r$(a);this.A=r$(a);this.B=r$(a);c.connect(this.g,b.Rk,0);c.connect(this.o,b.x,0);c.connect(this.A,b.y,0);c.connect(this.B,b.z,0);this.g.connect(d,0,e);this.o.connect(d,0,e);this.A.connect(d,0,e);this.B.connect(d,0,e);z$(this,0,0);this.g.gain.value=1-this.C},z$=function(a,b,c){var d=Math.sin(b);
b=Math.cos(b);var e=Math.sin(c);c=Math.cos(c);a.o.gain.value=a.C*(b*c*a.D-d*a.F);a.A.gain.value=a.C*(d*c*a.D+b*a.F);a.B.gain.value=a.C*e*a.D},B$=function(a,b,c){this.g=a;
this.A=c;this.B=this.o=null},C$=function(a,b,c){B$.call(this,a,0,c);
this.D=this.C=null},Twa=function(a){return 1==a?{Rk:2,
x:0,y:1,z:4,channelCount:6}:{Rk:0,x:3,y:1,z:2,channelCount:4}},D$=function(a){this.W=a;
this.o=null;this.g=new g.Qg(0,0,0,0);this.C=new g.Yd(0,0);this.B=this.A=0;g.YO&&g.jc(11)&&(this.o=g.re("CANVAS").getContext("2d"),g.jc(12.10532)||(this.A=3))},E$=function(a,b,c,d,e,f){e>=f?(d+=Math.random()*f|0,f=1):(c+=Math.random()*e|0,e=1);
Uwa(a,b,c,d,e,f,c,d,e,f);a=a.o.getImageData(c,d,e,f).data;for(b=0;b<a.length;b+=4)if(255<a[b]+a[b+1]+a[b+2]+a[b+3])return!0;return!1},Uwa=function(a,b,c,d,e,f,k,l,m,n){try{a.o.drawImage(b,c,d,e,f,k,l,m,n)}catch(q){if(!(q instanceof window.DOMException)||"IndexSizeError"!=q.name)throw q;
}},F$=function(a,b,c){this.G=b||!1;
this.D=c||null;this.C=new D$(a);this.g=Vwa},G$=function(a,b){F$.call(this,a);
this.F=b;this.B=null;this.o=g.YG("yt-player-webgl-anaglyph-3d-display-mode")||2;this.g=Wwa;this.A=!0},Ywa=function(a,b){this.g=Xwa;
this.B=a;this.C=!1;this.A=this.F=this.o=this.G=this.D=null;this.W=b},Zwa=function(a,b,c,d){b&&(b.uniform2f(a.F,c,d),2==a.B&&(1080>d?(b.uniform1f(a.A,.06),a.C=!0):(b.uniform1f(a.A,0),a.C=!1)))},H$=function(a,b){this.D=a;
this.F=b;this.A=!1;this.C=0;this.B={};this.o=null;this.g={}},$wa=function(a,b){var c=a.B[b];
if(!c||c.Zi==a.o&&!a.A)return!1;a.o=c.Zi;a.A=!1;a.C=a.o.A||a.C;return!0},I$=function(){this.g=new window.Float32Array(16);
this.A=new window.Float32Array(16);this.A.set([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);this.o=new window.Float32Array(16);this.o.set([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);this.identity()},axa=function(a,b,c,d){var e=Math.cos(b);
b=Math.sin(b);var f=Math.cos(c);c=Math.sin(c);var k=Math.cos(d);d=Math.sin(d);a.g.set([b*c*d+e*k,f*d,e*c*d-b*k,0,b*c*k-e*d,f*k,e*c*k+b*d,0,b*f,-c,e*f,0,0,0,0,1])},bxa=function(a,b){var c=Math.sin(b),d=Math.cos(b);
a.A.set([1,0,0,0,0,d,c,0,0,-c,d,0,0,0,0,1]);J$(a,a.A)},J$=function(a,b){a.o[0]=a.g[0]*b[0]+a.g[4]*b[1]+a.g[8]*b[2];
a.o[4]=a.g[0]*b[4]+a.g[4]*b[5]+a.g[8]*b[6];a.o[8]=a.g[0]*b[8]+a.g[4]*b[9]+a.g[8]*b[10];a.o[1]=a.g[1]*b[0]+a.g[5]*b[1]+a.g[9]*b[2];a.o[5]=a.g[1]*b[4]+a.g[5]*b[5]+a.g[9]*b[6];a.o[9]=a.g[1]*b[8]+a.g[5]*b[9]+a.g[9]*b[10];a.o[2]=a.g[2]*b[0]+a.g[6]*b[1]+a.g[10]*b[2];a.o[6]=a.g[2]*b[4]+a.g[6]*b[5]+a.g[10]*b[6];a.o[10]=a.g[2]*b[8]+a.g[6]*b[9]+a.g[10]*b[10];var c=a.g;a.g=a.o;a.o=c},K$=function(a){return Math.atan2(a.g[8],a.g[10])},cxa=function(a){var b=new window.Float32Array(3),c=y$(a);
b[0]=a[0]/c;b[1]=a[1]/c;b[2]=a[2]/c;a=1/(Math.abs(b[0])+Math.abs(b[1])+Math.abs(b[2]));b[0]*=a;b[1]*=a;b[2]*=a;0<b[2]&&(a=(1-Math.abs(b[0]))*(0<b[1]?1:-1),b[0]=(1-Math.abs(b[1]))*(0<b[0]?1:-1),b[1]=a);b[0]*=.5;b[1]*=.5;b[2]*=.5;b[0]+=.5;b[1]+=.5;a=Math.floor(256*b[0]);b=Math.floor(256*b[1]);256==a&&--a;256==b&&--b;return{x:a,y:255-b}},dxa=function(a){function b(a,b){var c,d=b;
for(c=0;a[c]!=b;++c){var e=a[c];a[c]=d;d=e}a[c]=d;return c}
var c=a.length,d=Array(2*c+3),e=0;d[0]=0;d[1]=c>>8&255;d[2]=c&255;for(var e=3,f=Array(256),k=Array(256),l=Array(256),m=0;256>m;++m)f[m]=m,k[m]=m,l[m]=0;for(var n=0,q=0,m=0;m<c;++m){var r=a[m],v=b(f,r);k[q]==r?l[q]+=4:0==(l[q]>>=1)&&(k[q]=r,l[q]=1);1<l[r]&&b(f,k[r]);q=r;0==v&&++n;if(0!=v||m+1==c){for(;0<n;)--n,0==n%2?d[e++]=0:d[e++]=254,n>>=1;if(255==v||254==v)d[e++]=255;0!=v&&(d[e++]=v)}}return d.slice(0,e)},exa=function(){this.D=this.G=this.o=this.F=this.A=0;
this.C=new window.Float32Array(3);this.B=-1;this.g=[]},L$=function(a,b){this.G=a;
this.F=null;this.na=b;this.g=new I$;this.J=.872;this.pa=this.sa=this.Ya=this.D=this.C=0;this.Sa=g.Gn;this.L=!0;this.ka=this.B=this.da=this.M=0;this.aa=90;this.fa=this.ca=0;this.S=new window.Float32Array(3);this.Pa=new exa;this.N=Math.PI/180},M$=function(a,b){L$.call(this,a,b);
var c=g.Y(a).experiments.o("html5_spherical_bicubic_mode");this.A=(this.o=0<c?new Ywa(c,a):null)?this.o.g:fxa;this.Ja=this.Oa=this.za=this.va=null;this.ba=new D$(a)},N$=function(a,b){M$.call(this,a,b);
this.ga=null;this.H=g.YG("yt-player-webgl-spherical-3d-display-mode")||1;this.Ka=!0;this.A=this.o?this.o.g:gxa},O$=function(a,b){L$.call(this,a,b);
this.ga=this.o=null;this.H=g.Y(a).experiments.g("enable_mesh_ps4")&&"CSS"in window&&"supports"in window.CSS&&window.CSS.supports("filter","map-to-mesh(url(p.msh), 100deg 60deg,matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),stereoscopic-left-right)");this.Ka="CSS"in window&&"supports"in window.CSS&&window.CSS.supports("filter","map-to-mesh(equirectangular, 100deg 60deg,matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),stereoscopic-left-right)");this.A=new H$(this.H,this.Ka);this.ba=
-1},P$=function(a){a.o&&(a.H||a.Ka?a.o.style.filter="":a.o.style.cssText=a.ga||a.o.style.cssText)},hxa=function(a){var b=!1;
if(g.PQ(a.G.ha())){if(a.H){var b=a.G.ha(),c;if(b.ua){var d=b.ua.g[b.La.id];c=d?d.F:null}else c=null;if(b.La){var e=b.La.video;if(e&&c)b:{b=a.A;d=e.width;e=e.height;b.g[c.g]||(b.g[c.g]=window.URL.createObjectURL(new window.Blob([c.o])));var f=b.B[e];if(f)if(f.Zi!=c)f.Zi=c,f.width=d;else{b=!1;break b}else b.B[e]={width:d,Zi:c};null==b.o&&$wa(b,e);b=!0}else b=!1}else b=!1;-1!=a.ba&&(b|=$wa(a.A,a.ba))}}else b=a.G.ha().lg()?3:0,d=a.A,d.A&&d.C==b?b=!1:(d.A=!0,d.C=b,b=!0);b&&a.o&&(b=a.A.stringValue())&&
(P$(a),a.H||a.Ka?a.o.style.filter=b:a.o.style.cssText+="; filter: "+b+";")},Q$=function(a,b){F$.call(this,a,!0,b);
this.o=null;this.W=a;this.g=ixa},jxa=function(a,b,c){this.F=c;
this.A=g.nV(a).g;this.D=10;this.C=!0;this.S=window.NaN;this.aa=this.M=this.ba=this.B=this.o=null;this.L=b;this.g=null;this.W=a;this.H=!1;this.G=!0;this.J=!1},lxa=function(a){a.o=g.re("CANVAS");
if(!a.o)return 1;a.F.appendChild(a.o);try{a.B=a.o.getContext("webgl")||a.o.getContext("experimental-webgl")}catch(d){return 2}if(null==a.B)return 3;var b=kxa(a);if(0!=b)return b;var b=a.B,c=b.createBuffer();b.bindBuffer(b.ARRAY_BUFFER,c);b.bufferData(b.ARRAY_BUFFER,new window.Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]),b.STATIC_DRAW);a.M=c;b=a.B;c=b.createTexture();b.activeTexture(b.TEXTURE0);b.bindTexture(b.TEXTURE_2D,c);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MIN_FILTER,b.LINEAR);b.texParameteri(b.TEXTURE_2D,
b.TEXTURE_MAG_FILTER,b.LINEAR);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_S,b.CLAMP_TO_EDGE);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_T,b.CLAMP_TO_EDGE);a.ba=c;b=a.B;b.clearColor(0,0,0,1);b.clear(b.COLOR_BUFFER_BIT|b.DEPTH_BUFFER_BIT);b.bindBuffer(b.ARRAY_BUFFER,a.M);b.vertexAttribPointer(a.N,3,b.FLOAT,!1,0,0);a.xk();a.A.crossOrigin="use-credentials";return 0},kxa=function(a){var b=a.B,c=b.createShader(b.VERTEX_SHADER);
b.shaderSource(c,a.g.Ki());b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))return 4;var d=b.createShader(b.FRAGMENT_SHADER);b.shaderSource(d,a.g.Fi());b.compileShader(d);if(!b.getShaderParameter(d,b.COMPILE_STATUS))return 5;var e=b.createProgram();b.attachShader(e,c);if(1!=b.getProgramParameter(e,b.ATTACHED_SHADERS))return 6;b.attachShader(e,d);if(2!=b.getProgramParameter(e,b.ATTACHED_SHADERS))return 7;b.linkProgram(e);if(0==b.getProgramParameter(e,b.LINK_STATUS))return 8;b.validateProgram(e);
b.useProgram(e);if(0==b.getProgramParameter(e,b.VALIDATE_STATUS))return 9;a.N=a.g.Ji(b,e);b.enableVertexAttribArray(a.N);a.aa=e;a.g.Vf(b,a.aa,a.F);return 0},R$=function(a){g.X.call(this,{K:"div",
X:"ytp-webgl-spherical-control",Z:{tabindex:0,"aria-label":g.U("YTP_SPHERICAL_CONTROL")},O:[g.dE?{K:"div",ea:["ytp-icon","ytp-icon-spherical-control"]}:{K:"svg",Z:{height:"100%",version:"1.1",viewBox:"0 0 50 50",width:"100%"},O:[{K:"circle",Qa:!0,Z:{cx:"25",cy:"25",fill:"#fff",r:"24"}},{K:"path",Qa:!0,Z:{d:"M11.46,29.41 L9.97,30.90 L4,24.95 L9.97,19 L11.46,20.48 L7.00,24.95 L11.46,29.41 M42.46,24.95 L38,20.48 L39.48,19 L45.46,24.95 L39.48,30.90 L38,29.41 L42.46,24.95 M24.5,42.43 L28.96,37.96 L30.45,39.45 L24.5,45.43 L18.54,39.45 L20.03,37.96 L24.5,42.43 M24.5,6.97 L20.03,11.43 L18.54,9.94 L24.5,3.96 L30.45,9.94 L28.96,11.43 L24.5,6.97 Z",
fill:"#999"}}]}]});this.g=a;this.A=this.B=null;this.D=new g.RL;g.M(this,this.D);this.C=[];this.ca=!1;this.da=null;this.F=new g.It((0,g.A)(this.UJ,this),null);g.M(this,this.F);this.aa=-1;this.S=this.G=this.J=this.H=this.M=this.L=0;this.N=!1;this.V(a,"videodatachange",this.Hr);this.V(a,"onApiChange",this.Hr);this.oa();this.Hr()},S$=function(a,b,c,d){a.M=g.Rd(b+a.M,-1,1);
a.J=g.Rd(c+a.J,-1,1);a.S=g.Rd(d+a.S,-1,1);a.ca||(a.ca=!0,g.S(a.element,"ytp-dragging"),a.aa=(0,g.G)(),a.F.start())},T$=function(a){a.F.stop();
a.ca=!1;a.M=0;a.J=0;a.S=0;a.C=[];g.eq(a.element,"ytp-dragging")},mxa=function(a,b,c,d,e,f){var k=f-a.aa;
a.H=(a.L*a.H+(b-e.yaw))/(k+a.L);a.G=(a.L*a.G+(c-e.pitch))/(k+a.L);a.aa=f;a.L=k;v$(a.g,{shader:"Spherical",yaw:b,pitch:c,fov:d})},U$=function(a,b){g.d1.call(this,g.U("YTP_THREED_SHORT"),7,a,b);
this.W=a;this.V(a,"videodatachange",this.B);this.F=null;this.B()},V$=function(a){g.OV.call(this,a);
this.B=new g.RL(this);g.M(this,this.B);this.C=null;this.D=new g.X({K:"div",X:"webgl"});g.M(this,this.D);this.W=a;this.o=null;var b=g.fV(a).D;b&&(b=b.A&&b.A.g)&&(b=new U$(a,b),g.M(this,b));b=new R$(a);g.M(this,b);g.DV(a,b.element,4);this.A=b;this.load()};
u$.prototype.initialize=function(){var a=(0,g.l4)();g.z(a)&&this.W.app.o.Dj(new g.QP("html5.webaudio",!1,{name:a}))};
u$.prototype.ma=function(){return this.B};
u$.prototype.dispose=function(){this.B=!0;p$(this);this.g=this.o=null};
w$.prototype.g=4;w$.prototype.set=function(a,b){b=b||0;for(var c=0;c<a.length&&b+c<this.length;c++)this[b+c]=a[c]};
w$.prototype.toString=Array.prototype.join;"undefined"==typeof window.Float32Array&&(w$.BYTES_PER_ELEMENT=4,w$.prototype.BYTES_PER_ELEMENT=w$.prototype.g,w$.prototype.set=w$.prototype.set,w$.prototype.toString=w$.prototype.toString,g.u("Float32Array",w$,void 0));x$.prototype.g=8;x$.prototype.set=function(a,b){b=b||0;for(var c=0;c<a.length&&b+c<this.length;c++)this[b+c]=a[c]};
x$.prototype.toString=Array.prototype.join;if("undefined"==typeof window.Float64Array){try{x$.BYTES_PER_ELEMENT=8}catch(a){}x$.prototype.BYTES_PER_ELEMENT=x$.prototype.g;x$.prototype.set=x$.prototype.set;x$.prototype.toString=x$.prototype.toString;g.u("Float64Array",x$,void 0)};var Wwa={vf:function(){return"varying vec2 a;attribute vec3 b;void main(){a=vec2((b.x+1.)*.5,(1.-b.y)*.5);gl_Position=vec4(b,1);}"},
sf:function(){return"precision mediump float;varying vec2 a;uniform sampler2D c;uniform int d;uniform mat4 e,f;void k(float g,float h){g*=.5;vec4 i,j;i=texture2D(c,vec2(g,h));j=texture2D(c,vec2(.5+g,h));gl_FragColor=e*i+f*j;}void main(){if(d==2)k(a.x,a.y);else if(d==1)gl_FragColor=texture2D(c,vec2(a.x*.5,a.y));}"},
bi:"c",mode:"d",CI:"e",DI:"f",kf:"b"};var Xwa={vf:function(){return"varying vec3 a;attribute vec3 b;void main(){gl_Position=vec4(b.xyz,1);a=b;}"},
sf:function(){return"precision mediump float;varying vec3 a;uniform sampler2D c;uniform mat4 d;uniform float e,f,j,k;uniform int g;uniform vec2 h;uniform vec4 i;mat4 l=mat4(-.043,.378,-.072,0,-.088,.734,-.113,0,0,-.018,1.226,0,0,0,0,1);mat4 m=mat4(.456,-.04,-.015,0,.5,-.038,-.021,0,.176,-.016,-.005,0,0,0,0,1);float B(float n){float o,p,q;o=n*n;p=o*abs(n);q=.5-.5*k;return ((12.-9.*k-6.*q)*p+(-18.+12.*k+6.*q)*o+(6.-2.*k))/6.;}float C(float n){n=abs(n);float o,p,q;o=n*n;p=o*n;q=.5-.5*k;return ((-k-6.*q)*p+(6.*k+30.*q)*o+(-12.*k-48.*q)*n+8.*k+24.*q)/6.;}vec4 D(sampler2D n,vec2 o){if(abs(k)>1.)return texture2D(n,o);vec2 p,q,r,s,t,u,v,w,x,A;p=1./h;o=o*h-.5;q=fract(o);r=o-q-.5;s=r+1.;t=r+2.;u=r+3.;r=vec2(mod(r.x*p.x,1.),r.y*p.y);s=vec2(mod(s.x*p.x,1.),s.y*p.y);t=vec2(mod(t.x*p.x,1.),t.y*p.y);u=vec2(mod(u.x*p.x,1.),u.y*p.y);v=vec2(C(q.x+1.),C(q.y+1.));w=vec2(B(q.x),B(q.y));x=vec2(B(1.-q.x),B(1.-q.y));A=vec2(C(2.-q.x),C(2.-q.y));return texture2D(n,vec2(r.x,r.y))*v.x*v.y+texture2D(n,vec2(s.x,r.y))*w.x*v.y+texture2D(n,vec2(t.x,r.y))*x.x*v.y+texture2D(n,vec2(u.x,r.y))*A.x*v.y+texture2D(n,vec2(r.x,s.y))*v.x*w.y+texture2D(n,vec2(s.x,s.y))*w.x*w.y+texture2D(n,vec2(t.x,s.y))*x.x*w.y+texture2D(n,vec2(u.x,s.y))*A.x*w.y+texture2D(n,vec2(r.x,t.y))*v.x*x.y+texture2D(n,vec2(s.x,t.y))*w.x*x.y+texture2D(n,vec2(t.x,t.y))*x.x*x.y+texture2D(n,vec2(u.x,t.y))*A.x*x.y+texture2D(n,vec2(r.x,u.y))*v.x*A.y+texture2D(n,vec2(s.x,u.y))*w.x*A.y+texture2D(n,vec2(t.x,u.y))*x.x*A.y+texture2D(n,vec2(u.x,u.y))*A.x*A.y;}vec4 E(vec3 n,vec4 o){if(j<=0.)return o;vec4 p,r;p=.5-abs(o-.5);float q=min(min(p.r,p.g),min(p.b,j));r=vec4(mod(n.x*12.9898+n.y*78.233,3.1415));r=fract(sin(r)*43755.23895*i);return o+mix(-q,q,dot(r,vec4(1))/4.);}void main(){vec3 n=vec3(a.x*tan(e),a.y*tan(f),-1);n=(d*vec4(n,1)).xyz;n=normalize(n);vec2 o=vec2(.5+atan(n.x,-1.*n.z)*.3183*.5,acos(n.y)*.3183);if(g==1){o.y*=.5;gl_FragColor=vec4(E(a,D(c,o)).rgb,1);}else if(g==2){o.y*=.5;vec4 p,q;p=m*E(a,D(c,o));o.y+=.5;q=l*E(a,D(c,o));gl_FragColor=vec4((p+q).rgb,1);}else gl_FragColor=vec4(E(a,D(c,o)).rgb,1);}"},
bi:"c",Ms:"d",Ks:"e",Ls:"f",PP:"g",SP:"h",RP:"i",TP:"j",OP:"k",kf:"b"};var Vwa={vf:function(){return"varying vec2 a;attribute vec3 b;void main(){a=vec2((b.x+1.)*.5,(1.-b.y)*.5);gl_Position=vec4(b,1);}"},
sf:function(){return"precision mediump float;varying vec2 a;uniform sampler2D c;void main(){gl_FragColor=texture2D(c,a);}"},
bi:"c",kf:"b"};var gxa={vf:function(){return"varying vec3 a;attribute vec3 b;void main(){gl_Position=vec4(b.xyz,1);a=b;}"},
sf:function(){return"precision mediump float;varying vec3 a;uniform sampler2D c;uniform int d;uniform mat4 e;uniform float f,g;mat4 h=mat4(-.043,.378,-.072,0,-.088,.734,-.113,0,0,-.018,1.226,0,0,0,0,1);mat4 i=mat4(.456,-.04,-.015,0,.5,-.038,-.021,0,.176,-.016,-.005,0,0,0,0,1);void n(float j,float k){k*=.5;vec4 l,m;l=texture2D(c,vec2(j,k));m=texture2D(c,vec2(j,.5+k));gl_FragColor=i*l+h*m;}void main(){vec3 j=vec3(a.x*tan(f),a.y*tan(g),-1);j=(e*vec4(j,1)).xyz;j=normalize(j);vec2 k=vec2(.5+atan(j.x,-1.*j.z)*.3183*.5,acos(j.y)*.3183);if(d==2)n(k.x,k.y);else{k.y*=.5;gl_FragColor=texture2D(c,k);}}"},
bi:"c",mode:"d",Ms:"e",Ks:"f",Ls:"g",kf:"b"};var fxa={vf:function(){return"varying vec3 a;attribute vec3 b;void main(){gl_Position=vec4(b.xyz,1);a=b;}"},
sf:function(){return"precision mediump float;varying vec3 a;uniform sampler2D c;uniform mat4 d;uniform float e,f;void main(){vec3 g=vec3(a.x*tan(e),a.y*tan(f),-1);g=(d*vec4(g,1)).xyz;g=normalize(g);vec2 h=vec2(.5+atan(g.x,-1.*g.z)*.3183*.5,acos(g.y)*.3183);gl_FragColor=vec4(texture2D(c,h).xyz,1);}"},
bi:"c",Ms:"d",Ks:"e",Ls:"f",kf:"b"};var ixa={vf:function(){return"varying vec2 a;attribute vec3 b;void main(){a=vec2((b.x+1.)*.5,(1.-b.y)*.5);gl_Position=vec4(b,1);}"},
sf:function(){return"precision mediump float;varying vec2 a;uniform sampler2D c,d;uniform float e,f,g;void main(){vec4 h,i;h=vec4(texture2D(c,a).xyz,1);i=texture2D(d,a+e);float j,k;j=max(max(h.x,h.y),h.z);k=f*smoothstep(0.,.1,j);k=k*smoothstep(0.,.1,1.-j);h.xyz=h.xyz+(i.x-g)*k;gl_FragColor=h;}"},
bi:"c",QP:"d",qP:"e",amount:"f",offset:"g",kf:"b"};A$.prototype.destroy=function(){delete this.g;delete this.o;delete this.A;delete this.B};B$.prototype.H=function(){p$(this.g);var a=Swa(this.g,this.A.channelCount),b=Rwa(this.g,2),c=65*Math.PI/180;this.o=new A$(this.g,this.A,a,b,0,.45,c);this.B=new A$(this.g,this.A,a,b,1,.45,-1*c);s$(this.g).connect(a);b.connect(t$(this.g))};
B$.prototype.G=function(){this.o.destroy();this.B.destroy();this.B=this.o=null;p$(this.g);s$(this.g).connect(t$(this.g))};
B$.prototype.F=function(a,b){this.o&&(z$(this.o,a,b),z$(this.B,a,b))};
B$.prototype.destroy=function(){this.o&&(p$(this.g),this.G())};g.C(C$,B$);C$.prototype.H=function(){p$(this.g);var a=Swa(this.g,this.A.channelCount),b=t$(this.g);b.channelCount=Math.min(6,b.maxChannelCount);b.channelInterpretation="discrete";var b=Rwa(this.g,6),c=Math.PI/6;this.o=new A$(this.g,this.A,a,b,0,.65,c);this.B=new A$(this.g,this.A,a,b,1,.65,-1*c);c=120*Math.PI/180;this.C=new A$(this.g,this.A,a,b,4,.65,c);this.D=new A$(this.g,this.A,a,b,5,.65,-1*c);s$(this.g).connect(a);b.connect(t$(this.g))};
C$.prototype.G=function(){this.C.destroy();this.D.destroy();this.D=this.C=null;C$.R.G.call(this)};
C$.prototype.F=function(a,b){this.o&&(z$(this.o,a,b),z$(this.B,a,b),z$(this.C,a,b),z$(this.D,a,b))};D$.prototype.Bd=function(a){if(null===this.o)return a;var b=new g.Yd(a.videoWidth,a.videoHeight);if(!g.Zd(b,this.C)&&(this.o.canvas.width=b.width,this.o.canvas.height=b.height,this.g.top=0,this.g.left=0,this.g.width=b.width,this.g.height=b.height,this.C=b,0<this.A)){this.A=3;var c=g.vZ(g.nV(this.W)),d=16/9;c<d?(this.g.width=b.width*c/d,this.g.left=Math.ceil(.5*(b.width-this.g.width)),this.g.width|=0):c>d&&(this.g.height=b.height*d/c,this.g.top=Math.ceil(.5*(b.height-this.g.height)),this.g.height|=
0)}0<this.A&&(this.B^=1,2<=this.g.top?(this.B?E$(this,a,0,0,this.g.width,this.g.top-1):E$(this,a,0,a.videoHeight-this.g.top+1,this.g.width,this.g.top-1))&&--this.A:2<=this.g.left&&(this.B?E$(this,a,0,0,this.g.left-1,this.g.height):E$(this,a,a.videoWidth-this.g.left+1,0,this.g.left-1,this.g.height))&&--this.A,0>=this.A&&(this.g.top=0,this.g.left=0,this.g.width=a.videoWidth,this.g.height=a.videoHeight));Uwa(this,a,this.g.left,this.g.top,this.g.width,this.g.height,0,0,this.C.width,this.C.height);return this.o.canvas};
D$.prototype.destroy=function(){null!=this.o&&(this.o.canvas.remove?this.o.canvas.remove():this.o.canvas.removeNode(!0),this.o=null)};g.h=F$.prototype;g.h.Ki=function(){return this.g.vf()};
g.h.Fi=function(){return this.g.sf()};
g.h.Ji=function(a,b){return a.getAttribLocation(b,this.g.kf)};
g.h.Vf=function(a,b){a.uniform1i(a.getUniformLocation(b,this.g.bi),0)};
g.h.yb=function(){};
g.h.il=function(a,b,c){this.G&&(360>=c?this.D(!0):this.D(!1))};
g.h.Uf=function(a,b){a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,this.C.Bd(b));a.drawArrays(a.TRIANGLE_STRIP,0,4)};
g.h.Wp=g.y;g.h.cA=function(){return!0};
g.h.Ii=function(){return{shader:"NoOp"}};
g.h.jl=function(){};
g.h.destroy=function(){this.C&&this.C.destroy()};g.C(G$,F$);g.h=G$.prototype;g.h.Ki=function(){return this.g.vf()};
g.h.Fi=function(){return this.g.sf()};
g.h.Ji=function(a,b){return a.getAttribLocation(b,this.g.kf)};
g.h.Vf=function(a,b,c){G$.R.Vf.call(this,a,b,c);a.uniformMatrix4fv(a.getUniformLocation(b,this.g.CI),!1,new window.Float32Array([.456,-.04,-.015,0,.5,-.038,-.021,0,.176,-.016,-.005,0,0,0,0,1]));a.uniformMatrix4fv(a.getUniformLocation(b,this.g.DI),!1,new window.Float32Array([-.043,.378,-.072,0,-.088,.734,-.113,0,0,-.018,1.226,0,0,0,0,1]));this.B=a.getUniformLocation(b,this.g.mode);a.uniform1i(this.B,this.o)};
g.h.Uf=function(a,b,c){this.A&&(a.uniform1i(this.B,this.o),this.A=!1);G$.R.Uf.call(this,a,b,c)};
g.h.Ii=function(){return{shader:"Anaglyph3D",displayMode:this.o}};
g.h.jl=function(a){"Anaglyph3D"==a.shader&&(void 0!=a.displayMode&&(this.o=(0,window.parseInt)(a.displayMode,10),g.XG("yt-player-webgl-anaglyph-3d-display-mode",this.o),this.A=!0),this.F())};H$.prototype.stringValue=function(){var a;switch(this.C){case 3:a="stereoscopic-top-bottom";break;case 1:a="stereoscopic-left-right";break;default:a="monoscopic"}a=", 100deg 60deg, matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),"+a+")";if(!this.A&&this.o&&this.D){var b;b="map-to-mesh("+("url("+this.g[this.o.g]+")");for(var c in this.B){var d=this.B[Number(c)];this.g[d.Zi.g]&&(b+=" "+d.width+" "+c+" url("+this.g[d.Zi.g]+")")}return b+a}return this.A?(this.F?"map-to-mesh(equirectangular":
"-cobalt-mtm(url(p.msh)")+a:"map-to-mesh(equirectangular"+a};
H$.prototype.destroy=function(){for(var a in this.g)window.URL.revokeObjectURL(this.g[Number(a)])};g.$E()&&(window.Float32Array.prototype.set=function(a,b){b=b||0;if(a.length)for(var c=0;c<a.length&&b+c<this.length;c++)this[b+c]=a[c]});
I$.prototype.identity=function(){this.g.set([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])};
I$.prototype.get=function(){return this.g};g.h=L$.prototype;g.h.Ki=function(){return""};
g.h.Fi=function(){return""};
g.h.Ji=function(){return window.NaN};
g.h.Vf=function(){var a;var b=this.G;a=b.ha();var c;if(c=a)a.md&&a.md.audio?(c=a.md.audio.spatialAudioType,c=!!c&&0!=c):c=!1;if(c){b=b.app;b.fa||(b.fa=new u$(b.g),b.fa.initialize(),g.M(b,b.fa));c=b.fa;var d=b.F;c.g?c.g!=d&&(p$(c),c.g=d,c.o=null):c.g=d;(b=b.fa)&&q$(b)?(a=a.md.audio.spatialAudioType,c=t$(b),a=6<=c.maxChannelCount&&!g.NN?new C$(b,0,Twa(a)):2<=c.maxChannelCount?new B$(b,0,Twa(a)):null):a=null}else a=null;if(this.F=a)this.F.H(),this.F.F(this.M,this.B)};
g.h.yb=function(){this.L=!0};
g.h.il=g.y;
g.h.Uf=function(a){var b=this.C,c=this.D;if(this.L){a.o>a.g?(this.C=this.J,this.D=Math.atan(Math.tan(this.J)*a.g/a.o)):(this.D=this.J,this.C=Math.atan(Math.tan(this.J)*a.o/a.g));if(this.Sa){axa(this.g,this.ka*this.N,this.aa*this.N,-this.ca*this.N);bxa(this.g,-Math.PI/2);a=this.g;var d=-this.fa*this.N,e=Math.sin(d),d=Math.cos(d);a.A.set([d,e,0,0,-e,d,0,0,0,0,1,0,0,0,0,1]);J$(a,a.A);this.da=this.da||K$(this.g);a=-Math.asin(this.g.g[9]);this.B=g.Rd(this.B,Math.max(-Math.PI/2,-Math.PI/2-a),Math.min(Math.PI/
2,Math.PI/2-a));e=this.g;axa(this.g,K$(this.g)-this.da+this.M,a+this.B,Math.atan2(e.g[1],e.g[5]))}else this.B=g.Rd(this.B,-Math.PI/2,Math.PI/2),this.g.identity(),a=this.g,d=this.M,e=Math.sin(d),d=Math.cos(d),a.A.set([d,0,-e,0,0,1,0,0,e,0,d,0,0,0,0,1]),J$(a,a.A),bxa(this.g,this.B);this.F&&this.F.F(K$(this.g),-Math.asin(this.g.g[9]));this.L=!1}a=(0,g.G)();if(this.Pa){this.S[0]=-this.g.get()[8];this.S[1]=-this.g.get()[9];this.S[2]=-this.g.get()[10];var e=this.Pa,d=this.S,f=this.G.getCurrentTime(),k=
a/1E3,l=this.G.Vk(),m=null,n,q,r;1==l?(n=e.A,r=e.G,q=f):(n=e.F,r=e.D,q=k);var v=0!=e.g.length;if(v){var x=150<=e.g.length;if(e.B!=l||.5<q-r||q<r||x){m=null;if(5<=e.g.length){for(var m=e.g,v=Array(2*m.length),B=x=0,F=0;F<m.length;++F)v[F]=m[F].x-x&255,v[F+m.length]=m[F].y-B&255,x=m[F].x,B=m[F].y;x=dxa(v);m=e.A;v=1==e.B?e.o:0;x=g.pc(x,!0);B="";for(F=x.length-1;0<=F&&"."==x.charAt(F);--F)B+="=";x=x.substring(0,x.length-B.length)+B;m={start:m,duration:v,data:x}}e.g=[];e.o=0;v=!1}}if(1==l||2==l||3==l){if(v)for(n=
n+e.o+.2;n<q;){x=(n-r)/(q-r);e.o+=.2;var O,J,v=e.C,B=d,F=x,x=new window.Float32Array(3),Za=y$(v),lb=y$(B),ia=(v[0]*B[0]+v[1]*B[1]+v[2]*B[2])/(Za*lb);.999999<ia?(Za=v[0],lb=v[1],v=v[2],x[0]=(B[0]-Za)*F+Za,x[1]=(B[1]-lb)*F+lb,x[2]=(B[2]-v)*F+v):(-.999999>ia?(ia=new window.Float32Array(3),J=(Za+lb)/2,v[0]?(J/=Math.sqrt(v[0]*v[0]+v[1]+v[1]),ia[0]=-v[1]*J,ia[1]=v[0]*J,ia[2]=0):(J/=Math.sqrt(v[2]*v[2]+v[1]+v[1]),ia[0]=0,ia[1]=-v[2]*J,ia[2]=v[1]*J),.5>=F?(lb=Za,B=ia,F*=2):(v=ia,F=2*F-1),J=Math.PI/2,O=1):
(J=Math.acos(ia),O=Math.sqrt(1-ia*ia)),ia=Math.sin((1-F)*J)/O/Za,J=Math.sin(F*J)/O/lb,F=(1-F)*Za+F*lb,x[0]=(v[0]*ia+B[0]*J)*F,x[1]=(v[1]*ia+B[1]*J)*F,x[2]=(v[2]*ia+B[2]*J)*F);v=x;e.g.push(cxa(v));n+=.2}else e.A=f,e.F=k,e.g.push(cxa(d)),e.o=0;e.C=d;e.G=f;e.D=k;e.B=l}e=m;e&&(d=g.lV(this.G.app))&&d.C&&(d=d.C.o,f=e.start,k=e.duration,e=e.data,g.KJ(d,g.BJ(d.g),"dir",[f.toFixed(3),k.toFixed(3),e]))}(this.Ya!=this.C||this.sa!=this.D)&&3E4<a-this.pa&&b==this.C&&c==this.D&&(this.Ya=this.C,this.sa=this.D,this.pa=
a,(b=g.lV(this.G.app))&&b.C&&(b=b.C.o,c=Math.round(360*this.C/Math.PI),a=Math.round(360*this.D/Math.PI),g.KJ(b,g.BJ(b.g),"fov",[c,a])))};
g.h.Wp=g.y;g.h.cA=function(){return!1};
g.h.Ii=function(){return{shader:"Spherical",yaw:this.M,pitch:this.B,alpha:this.ka,beta:this.aa,gamma:this.ca,orientation:this.fa,fov:this.J}};
g.h.jl=function(a){if("Spherical"==a.shader||"Spherical3D"==a.shader)a.hasOwnProperty("yaw")&&(this.M=a.yaw),a.hasOwnProperty("pitch")&&(this.B=a.pitch),a.hasOwnProperty("alpha")&&(this.ka=a.alpha),a.hasOwnProperty("beta")&&(this.aa=a.beta),a.hasOwnProperty("gamma")&&(this.ca=a.gamma),a.hasOwnProperty("orientation")&&(this.fa=a.orientation),a.hasOwnProperty("fov")&&(this.J=g.Rd(a.fov,.32,1.05)),this.L=!0,this.na()};
g.h.destroy=function(){this.F&&this.F.destroy()};g.C(M$,L$);g.h=M$.prototype;g.h.Ki=function(){return this.A.vf()};
g.h.Fi=function(){return this.A.sf()};
g.h.Ji=function(a,b){return a.getAttribLocation(b,this.A.kf)};
g.h.Vf=function(a,b,c){M$.R.Vf.call(this,a,b,c);this.Ja=a.getUniformLocation(b,this.A.Ms);this.va=a.getUniformLocation(b,this.A.Ks);this.za=a.getUniformLocation(b,this.A.Ls);this.Oa=a.getUniformLocation(b,this.A.bi);a.uniform1i(this.Oa,0);this.o&&(c=this.o,c.o=a.getUniformLocation(b,c.g.PP),c.F=a.getUniformLocation(b,c.g.SP),c.G=a.getUniformLocation(b,c.g.RP),c.A=a.getUniformLocation(b,c.g.TP),c.D=a.getUniformLocation(b,c.g.OP),a.uniform1i(c.o,0),a.uniform1f(c.A,0),(b=c.W.ha())&&b.La?Zwa(c,a,b.La.video.width,
b.La.video.height):(b=Math.min(4096,a.getParameter(3379)),a.uniform2f(c.F,b,b)),1==c.B||2==c.B?a.uniform1f(c.D,-.5):a.uniform1f(c.D,2))};
g.h.il=function(a,b,c){this.o&&Zwa(this.o,a,b,c)};
g.h.Uf=function(a,b,c,d){var e=this.L;M$.R.Uf.call(this,a,b,c,d);this.o&&(c=this.o,c.C&&a.uniform4f(c.G,Math.random()+1,Math.random()+1,Math.random()+1,Math.random()+1));e&&(a.uniform1f(this.va,this.C),a.uniform1f(this.za,this.D),a.uniformMatrix4fv(this.Ja,!1,this.g.get()));a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,this.ba.Bd(b));a.drawArrays(a.TRIANGLE_STRIP,0,4)};
g.h.destroy=function(){M$.R.destroy.call(this);this.ba&&this.ba.destroy()};g.C(N$,M$);g.h=N$.prototype;g.h.Ki=function(){return this.A.vf()};
g.h.Fi=function(){return this.A.sf()};
g.h.Ji=function(a,b){return a.getAttribLocation(b,this.A.kf)};
g.h.Vf=function(a,b,c){N$.R.Vf.call(this,a,b,c);this.o?a.uniform1i(this.o.o,this.H):(this.ga=a.getUniformLocation(b,this.A.mode),a.uniform1i(this.ga,this.H))};
g.h.Uf=function(a,b,c,d){this.Ka&&(this.o?a.uniform1i(this.o.o,this.H):a.uniform1i(this.ga,this.H),this.Ka=!1);N$.R.Uf.call(this,a,b,c,d)};
g.h.Ii=function(){var a=N$.R.Ii.call(this);a.shader="Spherical3D";a.displayMode=this.H;return a};
g.h.jl=function(a){void 0!=a.displayMode&&(this.H=(0,window.parseInt)(a.displayMode,10),g.XG("yt-player-webgl-spherical-3d-display-mode",this.H),this.Ka=!0,this.na());N$.R.jl.call(this,a)};g.C(O$,L$);O$.prototype.il=function(a,b,c){this.ba=c;hxa(this)};
O$.prototype.Wp=function(a){a!=this.o&&(P$(this),this.o=a,this.ga=a.style.cssText,hxa(this))};
O$.prototype.destroy=function(){O$.R.destroy.call(this);P$(this);this.A.destroy()};g.C(Q$,F$);g.h=Q$.prototype;g.h.Ki=function(){return this.g.vf()};
g.h.Fi=function(){return this.g.sf()};
g.h.Ji=function(a,b){return a.getAttribLocation(b,this.g.kf)};
g.h.Vf=function(a,b,c){Q$.R.Vf.call(this,a,b,c);c=new window.Uint8Array(4194304);for(var d=0;4194304>d;d++)c[d]=255*Math.random();d=a.createTexture();a.activeTexture(a.TEXTURE2);a.bindTexture(a.TEXTURE_2D,d);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.NEAREST);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.NEAREST);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.REPEAT);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.REPEAT);a.texImage2D(a.TEXTURE_2D,0,a.LUMINANCE,2048,2048,0,a.LUMINANCE,
a.UNSIGNED_BYTE,c);a.uniform1i(a.getUniformLocation(b,this.g.QP),2);a.uniform1f(a.getUniformLocation(b,this.g.amount),.05);a.uniform1f(a.getUniformLocation(b,this.g.offset),.5);this.o=a.getUniformLocation(b,this.g.qP);(b=this.W.ha())&&b.La&&this.il(a,b.La.video.width,b.La.video.height)};
g.h.Uf=function(a,b,c){a.uniform1f(this.o,Math.random());Q$.R.Uf.call(this,a,b,c)};
g.h.Ii=function(){return{shader:"WhiteNoise"}};g.h=jxa.prototype;g.h.xk=function(){this.H=!1;this.A.videoHeight!=this.S&&this.A.videoHeight&&this.A.videoWidth&&this.g&&(this.g.il(this.B,this.A.videoWidth,this.A.videoHeight),this.S=this.A.videoHeight);this.J&&this.g?this.g.Wp(this.A):this.B&&(this.A.videoWidth||this.A.videoHeight)&&this.g.Uf(this.B,this.A,this.M,this.ba);this.C&&this.Mn()};
g.h.wO=function(){this.C||(0,window.requestAnimationFrame)(this.xk.bind(this))};
g.h.yb=function(){if(0==this.D){var a;a=g.xZ(g.nV(this.W));var b,c,d,e=g.nV(this.W).Xa();this.g.cA()?("Anaglyph3D"!=this.L?b=!1:(b=g.vZ(g.nV(this.W)),c=this.W.ha(),b=(0,window.isNaN)(b)||c.tf("yt:stretch")||c.tf("yt:crop")?!1:.01>Math.abs(b-32/9)||.01>Math.abs(b-8/9)),b?(16*e.height/9>e.width?(b=e.width,c=9*b/16):(c=e.height,b=16*c/9),d=(e.height-c)/2,a=(e.width-b)/2):(b=a.width,c=a.height,d=a.top,a=a.left)):(b=e.width,c=e.height,a=d=0);a=new g.Qg(a|0,d|0,b|0,c|0);this.F.style.left=a.left+"px";this.F.style.top=
a.top+"px";this.o&&this.B&&(this.o.style.width=a.width+"px",this.o.style.height=a.height+"px",e=g.VO(),this.o.width=a.width*e,this.o.height=a.height*e,this.B.o=a.width*e,this.B.g=a.height*e,this.B.viewport(0,0,a.width*e,a.height*e),this.g.yb());this.C||(0,window.requestAnimationFrame)(this.xk.bind(this))}};
g.h.OF=function(a){this.G!=a&&this.o&&((this.G=a)?(this.F.appendChild(this.o),this.Mn(),g.MN||g.sc||g.eF||(this.A.style.display="none")):(g.ye(this.o),this.A.style.display=""))};
g.h.Mn=function(){!this.H&&this.G&&((0,window.requestAnimationFrame)(this.xk.bind(this)),this.H=!0)};g.p(R$,g.X);g.h=R$.prototype;
g.h.Hr=function(){var a=g.rV(this.g).shader;"Spherical"==a||"Spherical3D"==a?this.o||(a=g.nV(this.g).containerElement,g.S(this.g.getRootNode(),"ytp-webgl-spherical"),this.show(),this.B=new g.cG(a,!0,null,!0),this.B.subscribe("dragstart",this.XJ,this),this.B.subscribe("dragmove",this.Dy,this),this.B.subscribe("dragend",this.WJ,this),this.A=new g.cG(this.element,!0),this.A.subscribe("dragstart",this.WM,this),this.A.subscribe("dragend",this.VM,this),this.D.V(this.element,"keydown",this.YJ,this),this.D.V(this.element,
"keyup",this.cM,this),this.D.V(a,"click",this.VJ,this),this.D.V(window,"deviceorientation",this.SM,this),this.D.V(window,"devicemotion",this.AL,this)):this.o&&(T$(this),g.eq(this.g.getRootNode(),"ytp-webgl-spherical"),this.oa(),this.B.dispose(),this.B=null,this.A.dispose(),this.A=null,g.TL(this.D))};
g.h.WM=function(a,b,c){var d=g.ph(c);a=a-d.x-c.clientWidth/2;b=b-d.y-c.clientHeight/2;Math.abs(a)>Math.abs(b)?S$(this,0<a?-1:1,0,0):S$(this,0,0<b?-1:1,0)};
g.h.VM=function(){T$(this);this.F.start()};
g.h.XJ=function(a,b){T$(this);this.N=!1;this.da=new g.Vd(a,b);g.S(this.g.getRootNode(),"ytp-dragging")};
g.h.Dy=function(a,b){var c=new g.Vd(a,b),d=g.Xd(c,this.da);2<Math.sqrt(d.x*d.x+d.y*d.y)&&(this.N=!0);this.da=c;var c=g.rV(this.g),e=c.fov,f=Math.PI*e*.8,k=g.nV(this.g).Xa();d.scale(1/k.width*f,1/k.height*f);mxa(this,c.yaw+d.x,c.pitch+d.y,e,c,(0,g.G)())};
g.h.WJ=function(a,b){this.Dy(a,b);g.eq(this.g.getRootNode(),"ytp-dragging");this.F.start()};
g.h.VJ=function(a){this.N&&(a.stopPropagation(),this.N=!1)};
g.h.UJ=function(a){if(1E-5>Math.abs(this.H)&&1E-5>Math.abs(this.G)&&!this.M&&!this.J&&0==this.C.length)T$(this),this.G=this.H=0;else{var b=g.rV(this.g),c=b.yaw,d=b.pitch,e=b.fov,f=a-this.aa,k=nxa*e,c=c+(this.H+(k*this.M-.006*this.H)*f)*f,d=d+(this.G+(k*this.J-.006*this.G)*f)*f,e=e+k/.006*f*this.S/2;mxa(this,c,d,e,b,a);this.F.start()}};
g.h.YJ=function(a){!g.UF(a)&&this.Mw(g.QF(a))&&g.WF(a)};
g.h.cM=function(a){this.Ow(g.QF(a))};
g.h.Mw=function(a){if(-1<this.C.indexOf(a))return!0;var b=!1;switch(a){case 37:case 65:S$(this,1,0,0);b=!0;break;case 39:case 68:S$(this,-1,0,0);b=!0;break;case 38:case 87:S$(this,0,1,0);b=!0;break;case 40:case 83:S$(this,0,-1,0);b=!0;break;case 107:case 221:S$(this,0,0,-1);b=!0;break;case 109:case 219:S$(this,0,0,1),b=!0}b&&this.C.push(a);return b};
g.h.Ow=function(a){var b=this.C.indexOf(a);if(-1<b)switch(this.C.splice(b,1),a){case 37:case 65:S$(this,-1,0,0);break;case 39:case 68:S$(this,1,0,0);break;case 38:case 87:S$(this,0,-1,0);break;case 40:case 83:S$(this,0,1,0);break;case 107:case 221:S$(this,0,0,1);break;case 109:case 219:S$(this,0,0,-1)}0==this.C.length&&(this.ca=!1)};
g.h.SM=function(a){v$(this.g,{shader:"Spherical",alpha:a.alpha?a.alpha:0,beta:a.beta?a.beta:0,gamma:a.gamma?a.gamma:0})};
g.h.AL=function(a){if(a.acceleration&&a.accelerationIncludingGravity){var b=null,c=a.acceleration;a=a.accelerationIncludingGravity;8.3<a.x-c.x?b=90:-8.3>a.x-c.x?b=270:8.3<a.y-c.y&&(b=0);null!=b&&v$(this.g,{shader:"Spherical",orientation:b})}};
g.h.P=function(){g.eq(this.g.getRootNode(),"ytp-webgl-spherical");this.A&&(this.B.dispose(),this.B=null,this.A.dispose(),this.A=null);g.X.prototype.P.call(this)};
var nxa=.0035*.006;g.p(U$,g.d1);U$.prototype.Me=function(a){return g.U(oxa[(0,window.parseInt)(a,10)])};
U$.prototype.B=function(){var a=g.rV(this.W),b=a.shader;"Anaglyph3D"==b||"Spherical3D"==b?(this.F=b,this.enable(!0),a=a.displayMode,void 0!=a&&g.e1(this,a.toString())):this.enable(!1)};
U$.prototype.xi=function(a){g.d1.prototype.xi.call(this,a);a&&g.f1(this,[(1).toString(),(2).toString()])};
U$.prototype.gd=function(a){g.d1.prototype.gd.call(this,a);v$(this.W,{shader:this.F,displayMode:a});g.e1(this,a);this.A.bh();this.W.U("webglsettingschanged",g.rV(this.W))};
var W$={},oxa=(W$[1]="YTP_THREED_VIEWMODE_2D",W$[2]="YTP_THREED_VIEWMODE_ANAGLYPH",W$);g.C(V$,g.OV);V$.g=function(a){var b=g.Y(a).B.c.toLowerCase(),c=a.ha();a=g.Y(a);return g.AQ(c)?"Anaglyph3D":c.Oh()?"Spherical":c.lg()?"Spherical3D":a.experiments.g("enable_webgl_noop")&&"web"==b&&g.WO(a)?"NoOp":a.experiments.g("enable_white_noise")&&"web"==b&&(g.WO(a)||g.XO(a))?"WhiteNoise":null};
g.h=V$.prototype;g.h.aS=function(){this.o.yb()};
g.h.bS=function(){this.o.wO()};
g.h.ZR=function(a){var b=this.o,c=b.C;b.C=g.W(a.state,8);b.C&&!c&&b.Mn();g.W(a.state,8)&&this.C?(this.B.Fa(this.C),this.C=null):this.C||(this.C=this.B.V(this.g,"onVideoProgress",this.bS))};
g.h.XB=function(){var a;this.o?(a=this.o,a=a.g?a.g.Ii():{}):a={};return a};
g.h.YB=function(a){if(this.o){var b=this.o;b.g&&b.g.jl(a)}};
g.h.load=function(){V$.R.load.call(this);this.D.Ha(g.nV(this.g).containerElement);this.o=new jxa(this.W,V$.g(this.W),this.D.element);this.B.V(this.g,"resize",this.aS);this.B.V(this.g,"presentingplayerstatechange",this.ZR);var a;a:{a=this.o;a.g=null;var b=a.OF.bind(a),c=(0,g.A)(a.Mn,a);a.J=!1;if(a.J)switch(a.L){case "Spherical":a.g=new O$(a.W,c);a.xk();a.D=0;a=!0;break a}else{switch(a.L){case "Anaglyph3D":a.g=new G$(a.W,c);break;case "Spherical":a.g=new M$(a.W,c);break;case "WhiteNoise":a.g=new Q$(a.W,
b);break;case "NoOp":a.g=new F$(a.W,!0,b);break;case "Spherical3D":a.g=new N$(a.W,c)}if(a.g){a.D=lxa(a);if(0==a.D){!a.G||g.MN||g.sc||g.eF||(a.A.style.display="none");a.yb();a=!0;break a}a.W.app.o.Dj(new g.QP("html5.missingapi.webgl",!1,{code:a.D}));a.g=null}}a=!1}a?(g.CV(this.g,"webgl"),this.g.ya("onApiChange")):(g.CV(this.g,"webgl"),this.unload())};
g.h.unload=function(){V$.R.unload.call(this);var a=this.o;a.o&&(g.ye(a.o),a.o=null);a.B=null;a.C=!1;a.g&&a.g.destroy();a.g=null;a.A.removeAttribute("crossorigin");a.A.style.display="";a.D=10;this.o=null;this.D.detach();g.TL(this.B)};window._exportCheck==g.Aa&&g.u("ytmod.player.webgl",V$,void 0);})(_yt_player);
