.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH flexiproxy 1 "November 18, 2017" "" "FlexiProxy"

.SH NAME
flexiproxy \- framework for FlexiBee input/output modification

.SH SYNOPSIS
.B flexiproxy
.RI [ /path/to/dir/or/config.json ]
.br

.SH CONFIGURATION
You can change app configuration in /etc/flexiproxy/config.json file

.SH DESCRIPTION
This manual page explains the how to configure and run FlexiProxy
.B flexiproxy
program. This program takes input or output of FlexiBee and modify
it somehow

.PP
\fBflexiproxy\fP Modify FlexiBee web interface


