.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH flexiproxy 1 "November 18, 2016" "" "FlexiProxy"

.SH NAME
flexiproxy \- program for Import isdoc invoice items to FlexiBee

.SH SYNOPSIS
.B flexiproxy
.RI [ /path/to/dir/or/invoice.isdoc(x) ]
.br

.SH CONFIGURATION
You can change app configuration in /etc/flexiproxy/config.json file

.SH DESCRIPTION
This manual page explains the how to configure and run FlexiProxy
.B flexiproxy
program. This program takes ISDOC files from one given file or input directory
and parse it for unkown invoice items.
.PP
\fBflexiproxy\fP import all unknown invoice items to FlexiBee pricelist and storage


