src/FlexiProxy/plugins/html/*CustomColumn*.php		usr/share/flexiproxy/FlexiProxy/plugins/html/
src/FlexiProxy/plugins/json/*CustomColumn*.php		usr/share/flexiproxy/FlexiProxy/plugins/json/
src/FlexiProxy/plugins/js/*CustomColumn*.php		usr/share/flexiproxy/FlexiProxy/plugins/js/
src/FlexiProxy/CustomColumns.php                        usr/share/flexiproxy/FlexiProxy/
src/customcolumns.php                                   usr/share/flexiproxy/
src/FlexiProxy/ui/CustomColumnForm.php                  usr/share/flexiproxy/FlexiProxy/ui/
